#!/bin/bash

# command-line parameters
LOCAL_BWNDATA_INPUT_ZIPS=$1
BWNDATA_COLLECTION_NAME=$2
LOCAL_BWNDATA_OUTPUT_SEQUENCE_FILE=$3
TABLE_NAME=$4
TABLE_COLFAMS=$5 				# e.g. m:c
TABLE_REGION_CNT=$6				# e.g. 32
BULKLOAD_MAPPER=$7				

# optional parameter
HBASE_FULL_COLUMN_NAME=$7

# default parameters
IMPORTERS_JAR=../../../target/importers-1.0-SNAPSHOT-jar-with-dependencies.jar
IS_SNAPPY_COMPRESSED=true
HDFS_BWNDATA_SEQUENCE_FILE=${TABLE_NAME}_sf
HDFS_BWNDATA_SAMPLE_SEQUENCE_FILE=${TABLE_NAME}_sample_sf
HDFS_TABLE_HFILES_DIR=${TABLE_NAME}_hfiles

time ./import-to-sequence-files.sh ${IMPORTERS_JAR} ${LOCAL_BWNDATA_INPUT_ZIPS} ${BWNDATA_COLLECTION_NAME} ${LOCAL_BWNDATA_OUTPUT_SEQUENCE_FILE} ${IS_SNAPPY_COMPRESSED}
time ./create-presplited-table.sh ${IMPORTERS_JAR} ${HDFS_BWNDATA_SEQUENCE_FILE} ${HDFS_BWNDATA_SAMPLE_SEQUENCE_FILE} ${TABLE_NAME} ${TABLE_COLFAMS} ${TABLE_REGION_CNT} true ${LOCAL_BWNDATA_OUTPUT_SEQUENCE_FILE}
time ./bulkload-sequence-file.sh all ${IMPORTERS_JAR} ${HDFS_BWNDATA_SEQUENCE_FILE} ${HDFS_TABLE_HFILES_DIR} ${TABLE_NAME} ${BULKLOAD_MAPPER} ${HBASE_FULL_COLUMN_NAME}
