// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auditentry.proto

package pl.edu.icm.coansys.logsanalysis.models;

public final class AuditEntryProtos {
  private AuditEntryProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public enum Level
      implements com.google.protobuf.ProtocolMessageEnum {
    FATAL(0, 0),
    ERROR(1, 1),
    WARN(2, 2),
    INFO(3, 3),
    DEBUG(4, 4),
    TRACE(5, 5),
    ;
    
    
    public final int getNumber() { return value; }
    
    public static Level valueOf(int value) {
      switch (value) {
        case 0: return FATAL;
        case 1: return ERROR;
        case 2: return WARN;
        case 3: return INFO;
        case 4: return DEBUG;
        case 5: return TRACE;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<Level>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<Level>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Level>() {
            public Level findValueByNumber(int number) {
              return Level.valueOf(number)
    ;        }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return pl.edu.icm.coansys.logsanalysis.models.AuditEntryProtos.getDescriptor().getEnumTypes().get(0);
    }
    
    private static final Level[] VALUES = {
      FATAL, ERROR, WARN, INFO, DEBUG, TRACE, 
    };
    public static Level valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    private final int index;
    private final int value;
    private Level(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    static {
      pl.edu.icm.coansys.logsanalysis.models.AuditEntryProtos.getDescriptor();
    }
    
    // @@protoc_insertion_point(enum_scope:pl.edu.icm.coansys.logsanalysis.Level)
  }
  
  public static final class LogMessage extends
      com.google.protobuf.GeneratedMessage {
    // Use LogMessage.newBuilder() to construct.
    private LogMessage() {
      initFields();
    }
    private LogMessage(boolean noInit) {}
    
    private static final LogMessage defaultInstance;
    public static LogMessage getDefaultInstance() {
      return defaultInstance;
    }
    
    public LogMessage getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pl.edu.icm.coansys.logsanalysis.models.AuditEntryProtos.internal_static_pl_edu_icm_coansys_logsanalysis_LogMessage_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pl.edu.icm.coansys.logsanalysis.models.AuditEntryProtos.internal_static_pl_edu_icm_coansys_logsanalysis_LogMessage_fieldAccessorTable;
    }
    
    // required string event_id = 1;
    public static final int EVENT_ID_FIELD_NUMBER = 1;
    private boolean hasEventId;
    private java.lang.String eventId_ = "";
    public boolean hasEventId() { return hasEventId; }
    public java.lang.String getEventId() { return eventId_; }
    
    // required .pl.edu.icm.coansys.logsanalysis.Level level = 2;
    public static final int LEVEL_FIELD_NUMBER = 2;
    private boolean hasLevel;
    private pl.edu.icm.coansys.logsanalysis.models.AuditEntryProtos.Level level_;
    public boolean hasLevel() { return hasLevel; }
    public pl.edu.icm.coansys.logsanalysis.models.AuditEntryProtos.Level getLevel() { return level_; }
    
    // required string service_id = 3;
    public static final int SERVICE_ID_FIELD_NUMBER = 3;
    private boolean hasServiceId;
    private java.lang.String serviceId_ = "";
    public boolean hasServiceId() { return hasServiceId; }
    public java.lang.String getServiceId() { return serviceId_; }
    
    // required string event_type = 4;
    public static final int EVENT_TYPE_FIELD_NUMBER = 4;
    private boolean hasEventType;
    private java.lang.String eventType_ = "";
    public boolean hasEventType() { return hasEventType; }
    public java.lang.String getEventType() { return eventType_; }
    
    // required int64 timestamp = 5;
    public static final int TIMESTAMP_FIELD_NUMBER = 5;
    private boolean hasTimestamp;
    private long timestamp_ = 0L;
    public boolean hasTimestamp() { return hasTimestamp; }
    public long getTimestamp() { return timestamp_; }
    
    // repeated string arg = 6;
    public static final int ARG_FIELD_NUMBER = 6;
    private java.util.List<java.lang.String> arg_ =
      java.util.Collections.emptyList();
    public java.util.List<java.lang.String> getArgList() {
      return arg_;
    }
    public int getArgCount() { return arg_.size(); }
    public java.lang.String getArg(int index) {
      return arg_.get(index);
    }
    
    private void initFields() {
      level_ = pl.edu.icm.coansys.logsanalysis.models.AuditEntryProtos.Level.FATAL;
    }
    public final boolean isInitialized() {
      if (!hasEventId) return false;
      if (!hasLevel) return false;
      if (!hasServiceId) return false;
      if (!hasEventType) return false;
      if (!hasTimestamp) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasEventId()) {
        output.writeString(1, getEventId());
      }
      if (hasLevel()) {
        output.writeEnum(2, getLevel().getNumber());
      }
      if (hasServiceId()) {
        output.writeString(3, getServiceId());
      }
      if (hasEventType()) {
        output.writeString(4, getEventType());
      }
      if (hasTimestamp()) {
        output.writeInt64(5, getTimestamp());
      }
      for (java.lang.String element : getArgList()) {
        output.writeString(6, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasEventId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getEventId());
      }
      if (hasLevel()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, getLevel().getNumber());
      }
      if (hasServiceId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getServiceId());
      }
      if (hasEventType()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(4, getEventType());
      }
      if (hasTimestamp()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, getTimestamp());
      }
      {
        int dataSize = 0;
        for (java.lang.String element : getArgList()) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeStringSizeNoTag(element);
        }
        size += dataSize;
        size += 1 * getArgList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static pl.edu.icm.coansys.logsanalysis.models.AuditEntryProtos.LogMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static pl.edu.icm.coansys.logsanalysis.models.AuditEntryProtos.LogMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static pl.edu.icm.coansys.logsanalysis.models.AuditEntryProtos.LogMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static pl.edu.icm.coansys.logsanalysis.models.AuditEntryProtos.LogMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static pl.edu.icm.coansys.logsanalysis.models.AuditEntryProtos.LogMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static pl.edu.icm.coansys.logsanalysis.models.AuditEntryProtos.LogMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static pl.edu.icm.coansys.logsanalysis.models.AuditEntryProtos.LogMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static pl.edu.icm.coansys.logsanalysis.models.AuditEntryProtos.LogMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static pl.edu.icm.coansys.logsanalysis.models.AuditEntryProtos.LogMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static pl.edu.icm.coansys.logsanalysis.models.AuditEntryProtos.LogMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(pl.edu.icm.coansys.logsanalysis.models.AuditEntryProtos.LogMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private pl.edu.icm.coansys.logsanalysis.models.AuditEntryProtos.LogMessage result;
      
      // Construct using pl.edu.icm.coansys.logsanalysis.models.AuditEntryProtos.LogMessage.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new pl.edu.icm.coansys.logsanalysis.models.AuditEntryProtos.LogMessage();
        return builder;
      }
      
      protected pl.edu.icm.coansys.logsanalysis.models.AuditEntryProtos.LogMessage internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new pl.edu.icm.coansys.logsanalysis.models.AuditEntryProtos.LogMessage();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pl.edu.icm.coansys.logsanalysis.models.AuditEntryProtos.LogMessage.getDescriptor();
      }
      
      public pl.edu.icm.coansys.logsanalysis.models.AuditEntryProtos.LogMessage getDefaultInstanceForType() {
        return pl.edu.icm.coansys.logsanalysis.models.AuditEntryProtos.LogMessage.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public pl.edu.icm.coansys.logsanalysis.models.AuditEntryProtos.LogMessage build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private pl.edu.icm.coansys.logsanalysis.models.AuditEntryProtos.LogMessage buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public pl.edu.icm.coansys.logsanalysis.models.AuditEntryProtos.LogMessage buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.arg_ != java.util.Collections.EMPTY_LIST) {
          result.arg_ =
            java.util.Collections.unmodifiableList(result.arg_);
        }
        pl.edu.icm.coansys.logsanalysis.models.AuditEntryProtos.LogMessage returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pl.edu.icm.coansys.logsanalysis.models.AuditEntryProtos.LogMessage) {
          return mergeFrom((pl.edu.icm.coansys.logsanalysis.models.AuditEntryProtos.LogMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(pl.edu.icm.coansys.logsanalysis.models.AuditEntryProtos.LogMessage other) {
        if (other == pl.edu.icm.coansys.logsanalysis.models.AuditEntryProtos.LogMessage.getDefaultInstance()) return this;
        if (other.hasEventId()) {
          setEventId(other.getEventId());
        }
        if (other.hasLevel()) {
          setLevel(other.getLevel());
        }
        if (other.hasServiceId()) {
          setServiceId(other.getServiceId());
        }
        if (other.hasEventType()) {
          setEventType(other.getEventType());
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (!other.arg_.isEmpty()) {
          if (result.arg_.isEmpty()) {
            result.arg_ = new java.util.ArrayList<java.lang.String>();
          }
          result.arg_.addAll(other.arg_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setEventId(input.readString());
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              pl.edu.icm.coansys.logsanalysis.models.AuditEntryProtos.Level value = pl.edu.icm.coansys.logsanalysis.models.AuditEntryProtos.Level.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                setLevel(value);
              }
              break;
            }
            case 26: {
              setServiceId(input.readString());
              break;
            }
            case 34: {
              setEventType(input.readString());
              break;
            }
            case 40: {
              setTimestamp(input.readInt64());
              break;
            }
            case 50: {
              addArg(input.readString());
              break;
            }
          }
        }
      }
      
      
      // required string event_id = 1;
      public boolean hasEventId() {
        return result.hasEventId();
      }
      public java.lang.String getEventId() {
        return result.getEventId();
      }
      public Builder setEventId(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasEventId = true;
        result.eventId_ = value;
        return this;
      }
      public Builder clearEventId() {
        result.hasEventId = false;
        result.eventId_ = getDefaultInstance().getEventId();
        return this;
      }
      
      // required .pl.edu.icm.coansys.logsanalysis.Level level = 2;
      public boolean hasLevel() {
        return result.hasLevel();
      }
      public pl.edu.icm.coansys.logsanalysis.models.AuditEntryProtos.Level getLevel() {
        return result.getLevel();
      }
      public Builder setLevel(pl.edu.icm.coansys.logsanalysis.models.AuditEntryProtos.Level value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasLevel = true;
        result.level_ = value;
        return this;
      }
      public Builder clearLevel() {
        result.hasLevel = false;
        result.level_ = pl.edu.icm.coansys.logsanalysis.models.AuditEntryProtos.Level.FATAL;
        return this;
      }
      
      // required string service_id = 3;
      public boolean hasServiceId() {
        return result.hasServiceId();
      }
      public java.lang.String getServiceId() {
        return result.getServiceId();
      }
      public Builder setServiceId(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasServiceId = true;
        result.serviceId_ = value;
        return this;
      }
      public Builder clearServiceId() {
        result.hasServiceId = false;
        result.serviceId_ = getDefaultInstance().getServiceId();
        return this;
      }
      
      // required string event_type = 4;
      public boolean hasEventType() {
        return result.hasEventType();
      }
      public java.lang.String getEventType() {
        return result.getEventType();
      }
      public Builder setEventType(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasEventType = true;
        result.eventType_ = value;
        return this;
      }
      public Builder clearEventType() {
        result.hasEventType = false;
        result.eventType_ = getDefaultInstance().getEventType();
        return this;
      }
      
      // required int64 timestamp = 5;
      public boolean hasTimestamp() {
        return result.hasTimestamp();
      }
      public long getTimestamp() {
        return result.getTimestamp();
      }
      public Builder setTimestamp(long value) {
        result.hasTimestamp = true;
        result.timestamp_ = value;
        return this;
      }
      public Builder clearTimestamp() {
        result.hasTimestamp = false;
        result.timestamp_ = 0L;
        return this;
      }
      
      // repeated string arg = 6;
      public java.util.List<java.lang.String> getArgList() {
        return java.util.Collections.unmodifiableList(result.arg_);
      }
      public int getArgCount() {
        return result.getArgCount();
      }
      public java.lang.String getArg(int index) {
        return result.getArg(index);
      }
      public Builder setArg(int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.arg_.set(index, value);
        return this;
      }
      public Builder addArg(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  if (result.arg_.isEmpty()) {
          result.arg_ = new java.util.ArrayList<java.lang.String>();
        }
        result.arg_.add(value);
        return this;
      }
      public Builder addAllArg(
          java.lang.Iterable<? extends java.lang.String> values) {
        if (result.arg_.isEmpty()) {
          result.arg_ = new java.util.ArrayList<java.lang.String>();
        }
        super.addAll(values, result.arg_);
        return this;
      }
      public Builder clearArg() {
        result.arg_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:pl.edu.icm.coansys.logsanalysis.LogMessage)
    }
    
    static {
      defaultInstance = new LogMessage(true);
      pl.edu.icm.coansys.logsanalysis.models.AuditEntryProtos.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:pl.edu.icm.coansys.logsanalysis.LogMessage)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_pl_edu_icm_coansys_logsanalysis_LogMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_pl_edu_icm_coansys_logsanalysis_LogMessage_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020auditentry.proto\022\037pl.edu.icm.coansys.l" +
      "ogsanalysis\"\235\001\n\nLogMessage\022\020\n\010event_id\030\001" +
      " \002(\t\0225\n\005level\030\002 \002(\0162&.pl.edu.icm.coansys" +
      ".logsanalysis.Level\022\022\n\nservice_id\030\003 \002(\t\022" +
      "\022\n\nevent_type\030\004 \002(\t\022\021\n\ttimestamp\030\005 \002(\003\022\013" +
      "\n\003arg\030\006 \003(\t*G\n\005Level\022\t\n\005FATAL\020\000\022\t\n\005ERROR" +
      "\020\001\022\010\n\004WARN\020\002\022\010\n\004INFO\020\003\022\t\n\005DEBUG\020\004\022\t\n\005TRA" +
      "CE\020\005B:\n&pl.edu.icm.coansys.logsanalysis." +
      "modelsB\020AuditEntryProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_pl_edu_icm_coansys_logsanalysis_LogMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_pl_edu_icm_coansys_logsanalysis_LogMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_pl_edu_icm_coansys_logsanalysis_LogMessage_descriptor,
              new java.lang.String[] { "EventId", "Level", "ServiceId", "EventType", "Timestamp", "Arg", },
              pl.edu.icm.coansys.logsanalysis.models.AuditEntryProtos.LogMessage.class,
              pl.edu.icm.coansys.logsanalysis.models.AuditEntryProtos.LogMessage.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
