/*
 * This file is part of CoAnSys project.
 * Copyright (c) 2012-2015 ICM-UW
 * 
 * CoAnSys is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.

 * CoAnSys is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with CoAnSys. If not, see <http://www.gnu.org/licenses/>.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: disambig_auth_out.proto

package pl.edu.icm.coansys.models;

public final class DisambiguationAuthorProtos {
  private DisambiguationAuthorProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface DisambiguationAuthorOutOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string docId = 1;
    boolean hasDocId();
    String getDocId();
    
    // repeated .pl.edu.icm.coansys.models.ContributorDescription contributorDescription = 2;
    java.util.List<pl.edu.icm.coansys.models.DisambiguationAuthorProtos.ContributorDescription> 
        getContributorDescriptionList();
    pl.edu.icm.coansys.models.DisambiguationAuthorProtos.ContributorDescription getContributorDescription(int index);
    int getContributorDescriptionCount();
    java.util.List<? extends pl.edu.icm.coansys.models.DisambiguationAuthorProtos.ContributorDescriptionOrBuilder> 
        getContributorDescriptionOrBuilderList();
    pl.edu.icm.coansys.models.DisambiguationAuthorProtos.ContributorDescriptionOrBuilder getContributorDescriptionOrBuilder(
        int index);
    
    // repeated .pl.edu.icm.coansys.models.Auxiliar auxs = 3;
    java.util.List<pl.edu.icm.coansys.models.DisambiguationAuthorProtos.Auxiliar> 
        getAuxsList();
    pl.edu.icm.coansys.models.DisambiguationAuthorProtos.Auxiliar getAuxs(int index);
    int getAuxsCount();
    java.util.List<? extends pl.edu.icm.coansys.models.DisambiguationAuthorProtos.AuxiliarOrBuilder> 
        getAuxsOrBuilderList();
    pl.edu.icm.coansys.models.DisambiguationAuthorProtos.AuxiliarOrBuilder getAuxsOrBuilder(
        int index);
  }
  public static final class DisambiguationAuthorOut extends
      com.google.protobuf.GeneratedMessage
      implements DisambiguationAuthorOutOrBuilder {
    // Use DisambiguationAuthorOut.newBuilder() to construct.
    private DisambiguationAuthorOut(Builder builder) {
      super(builder);
    }
    private DisambiguationAuthorOut(boolean noInit) {}
    
    private static final DisambiguationAuthorOut defaultInstance;
    public static DisambiguationAuthorOut getDefaultInstance() {
      return defaultInstance;
    }
    
    public DisambiguationAuthorOut getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pl.edu.icm.coansys.models.DisambiguationAuthorProtos.internal_static_pl_edu_icm_coansys_models_DisambiguationAuthorOut_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pl.edu.icm.coansys.models.DisambiguationAuthorProtos.internal_static_pl_edu_icm_coansys_models_DisambiguationAuthorOut_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string docId = 1;
    public static final int DOCID_FIELD_NUMBER = 1;
    private java.lang.Object docId_;
    public boolean hasDocId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getDocId() {
      java.lang.Object ref = docId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          docId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getDocIdBytes() {
      java.lang.Object ref = docId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        docId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated .pl.edu.icm.coansys.models.ContributorDescription contributorDescription = 2;
    public static final int CONTRIBUTORDESCRIPTION_FIELD_NUMBER = 2;
    private java.util.List<pl.edu.icm.coansys.models.DisambiguationAuthorProtos.ContributorDescription> contributorDescription_;
    public java.util.List<pl.edu.icm.coansys.models.DisambiguationAuthorProtos.ContributorDescription> getContributorDescriptionList() {
      return contributorDescription_;
    }
    public java.util.List<? extends pl.edu.icm.coansys.models.DisambiguationAuthorProtos.ContributorDescriptionOrBuilder> 
        getContributorDescriptionOrBuilderList() {
      return contributorDescription_;
    }
    public int getContributorDescriptionCount() {
      return contributorDescription_.size();
    }
    public pl.edu.icm.coansys.models.DisambiguationAuthorProtos.ContributorDescription getContributorDescription(int index) {
      return contributorDescription_.get(index);
    }
    public pl.edu.icm.coansys.models.DisambiguationAuthorProtos.ContributorDescriptionOrBuilder getContributorDescriptionOrBuilder(
        int index) {
      return contributorDescription_.get(index);
    }
    
    // repeated .pl.edu.icm.coansys.models.Auxiliar auxs = 3;
    public static final int AUXS_FIELD_NUMBER = 3;
    private java.util.List<pl.edu.icm.coansys.models.DisambiguationAuthorProtos.Auxiliar> auxs_;
    public java.util.List<pl.edu.icm.coansys.models.DisambiguationAuthorProtos.Auxiliar> getAuxsList() {
      return auxs_;
    }
    public java.util.List<? extends pl.edu.icm.coansys.models.DisambiguationAuthorProtos.AuxiliarOrBuilder> 
        getAuxsOrBuilderList() {
      return auxs_;
    }
    public int getAuxsCount() {
      return auxs_.size();
    }
    public pl.edu.icm.coansys.models.DisambiguationAuthorProtos.Auxiliar getAuxs(int index) {
      return auxs_.get(index);
    }
    public pl.edu.icm.coansys.models.DisambiguationAuthorProtos.AuxiliarOrBuilder getAuxsOrBuilder(
        int index) {
      return auxs_.get(index);
    }
    
    private void initFields() {
      docId_ = "";
      contributorDescription_ = java.util.Collections.emptyList();
      auxs_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasDocId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getContributorDescriptionCount(); i++) {
        if (!getContributorDescription(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getDocIdBytes());
      }
      for (int i = 0; i < contributorDescription_.size(); i++) {
        output.writeMessage(2, contributorDescription_.get(i));
      }
      for (int i = 0; i < auxs_.size(); i++) {
        output.writeMessage(3, auxs_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getDocIdBytes());
      }
      for (int i = 0; i < contributorDescription_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, contributorDescription_.get(i));
      }
      for (int i = 0; i < auxs_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, auxs_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static pl.edu.icm.coansys.models.DisambiguationAuthorProtos.DisambiguationAuthorOut parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static pl.edu.icm.coansys.models.DisambiguationAuthorProtos.DisambiguationAuthorOut parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static pl.edu.icm.coansys.models.DisambiguationAuthorProtos.DisambiguationAuthorOut parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static pl.edu.icm.coansys.models.DisambiguationAuthorProtos.DisambiguationAuthorOut parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static pl.edu.icm.coansys.models.DisambiguationAuthorProtos.DisambiguationAuthorOut parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static pl.edu.icm.coansys.models.DisambiguationAuthorProtos.DisambiguationAuthorOut parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static pl.edu.icm.coansys.models.DisambiguationAuthorProtos.DisambiguationAuthorOut parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static pl.edu.icm.coansys.models.DisambiguationAuthorProtos.DisambiguationAuthorOut parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static pl.edu.icm.coansys.models.DisambiguationAuthorProtos.DisambiguationAuthorOut parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static pl.edu.icm.coansys.models.DisambiguationAuthorProtos.DisambiguationAuthorOut parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(pl.edu.icm.coansys.models.DisambiguationAuthorProtos.DisambiguationAuthorOut prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements pl.edu.icm.coansys.models.DisambiguationAuthorProtos.DisambiguationAuthorOutOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pl.edu.icm.coansys.models.DisambiguationAuthorProtos.internal_static_pl_edu_icm_coansys_models_DisambiguationAuthorOut_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pl.edu.icm.coansys.models.DisambiguationAuthorProtos.internal_static_pl_edu_icm_coansys_models_DisambiguationAuthorOut_fieldAccessorTable;
      }
      
      // Construct using pl.edu.icm.coansys.models.DisambiguationAuthorProtos.DisambiguationAuthorOut.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getContributorDescriptionFieldBuilder();
          getAuxsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        docId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (contributorDescriptionBuilder_ == null) {
          contributorDescription_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          contributorDescriptionBuilder_.clear();
        }
        if (auxsBuilder_ == null) {
          auxs_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          auxsBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pl.edu.icm.coansys.models.DisambiguationAuthorProtos.DisambiguationAuthorOut.getDescriptor();
      }
      
      public pl.edu.icm.coansys.models.DisambiguationAuthorProtos.DisambiguationAuthorOut getDefaultInstanceForType() {
        return pl.edu.icm.coansys.models.DisambiguationAuthorProtos.DisambiguationAuthorOut.getDefaultInstance();
      }
      
      public pl.edu.icm.coansys.models.DisambiguationAuthorProtos.DisambiguationAuthorOut build() {
        pl.edu.icm.coansys.models.DisambiguationAuthorProtos.DisambiguationAuthorOut result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private pl.edu.icm.coansys.models.DisambiguationAuthorProtos.DisambiguationAuthorOut buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        pl.edu.icm.coansys.models.DisambiguationAuthorProtos.DisambiguationAuthorOut result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public pl.edu.icm.coansys.models.DisambiguationAuthorProtos.DisambiguationAuthorOut buildPartial() {
        pl.edu.icm.coansys.models.DisambiguationAuthorProtos.DisambiguationAuthorOut result = new pl.edu.icm.coansys.models.DisambiguationAuthorProtos.DisambiguationAuthorOut(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.docId_ = docId_;
        if (contributorDescriptionBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            contributorDescription_ = java.util.Collections.unmodifiableList(contributorDescription_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.contributorDescription_ = contributorDescription_;
        } else {
          result.contributorDescription_ = contributorDescriptionBuilder_.build();
        }
        if (auxsBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            auxs_ = java.util.Collections.unmodifiableList(auxs_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.auxs_ = auxs_;
        } else {
          result.auxs_ = auxsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pl.edu.icm.coansys.models.DisambiguationAuthorProtos.DisambiguationAuthorOut) {
          return mergeFrom((pl.edu.icm.coansys.models.DisambiguationAuthorProtos.DisambiguationAuthorOut)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(pl.edu.icm.coansys.models.DisambiguationAuthorProtos.DisambiguationAuthorOut other) {
        if (other == pl.edu.icm.coansys.models.DisambiguationAuthorProtos.DisambiguationAuthorOut.getDefaultInstance()) return this;
        if (other.hasDocId()) {
          setDocId(other.getDocId());
        }
        if (contributorDescriptionBuilder_ == null) {
          if (!other.contributorDescription_.isEmpty()) {
            if (contributorDescription_.isEmpty()) {
              contributorDescription_ = other.contributorDescription_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureContributorDescriptionIsMutable();
              contributorDescription_.addAll(other.contributorDescription_);
            }
            onChanged();
          }
        } else {
          if (!other.contributorDescription_.isEmpty()) {
            if (contributorDescriptionBuilder_.isEmpty()) {
              contributorDescriptionBuilder_.dispose();
              contributorDescriptionBuilder_ = null;
              contributorDescription_ = other.contributorDescription_;
              bitField0_ = (bitField0_ & ~0x00000002);
              contributorDescriptionBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getContributorDescriptionFieldBuilder() : null;
            } else {
              contributorDescriptionBuilder_.addAllMessages(other.contributorDescription_);
            }
          }
        }
        if (auxsBuilder_ == null) {
          if (!other.auxs_.isEmpty()) {
            if (auxs_.isEmpty()) {
              auxs_ = other.auxs_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureAuxsIsMutable();
              auxs_.addAll(other.auxs_);
            }
            onChanged();
          }
        } else {
          if (!other.auxs_.isEmpty()) {
            if (auxsBuilder_.isEmpty()) {
              auxsBuilder_.dispose();
              auxsBuilder_ = null;
              auxs_ = other.auxs_;
              bitField0_ = (bitField0_ & ~0x00000004);
              auxsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getAuxsFieldBuilder() : null;
            } else {
              auxsBuilder_.addAllMessages(other.auxs_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasDocId()) {
          
          return false;
        }
        for (int i = 0; i < getContributorDescriptionCount(); i++) {
          if (!getContributorDescription(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              docId_ = input.readBytes();
              break;
            }
            case 18: {
              pl.edu.icm.coansys.models.DisambiguationAuthorProtos.ContributorDescription.Builder subBuilder = pl.edu.icm.coansys.models.DisambiguationAuthorProtos.ContributorDescription.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addContributorDescription(subBuilder.buildPartial());
              break;
            }
            case 26: {
              pl.edu.icm.coansys.models.DisambiguationAuthorProtos.Auxiliar.Builder subBuilder = pl.edu.icm.coansys.models.DisambiguationAuthorProtos.Auxiliar.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addAuxs(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string docId = 1;
      private java.lang.Object docId_ = "";
      public boolean hasDocId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getDocId() {
        java.lang.Object ref = docId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          docId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setDocId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        docId_ = value;
        onChanged();
        return this;
      }
      public Builder clearDocId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        docId_ = getDefaultInstance().getDocId();
        onChanged();
        return this;
      }
      void setDocId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        docId_ = value;
        onChanged();
      }
      
      // repeated .pl.edu.icm.coansys.models.ContributorDescription contributorDescription = 2;
      private java.util.List<pl.edu.icm.coansys.models.DisambiguationAuthorProtos.ContributorDescription> contributorDescription_ =
        java.util.Collections.emptyList();
      private void ensureContributorDescriptionIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          contributorDescription_ = new java.util.ArrayList<pl.edu.icm.coansys.models.DisambiguationAuthorProtos.ContributorDescription>(contributorDescription_);
          bitField0_ |= 0x00000002;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          pl.edu.icm.coansys.models.DisambiguationAuthorProtos.ContributorDescription, pl.edu.icm.coansys.models.DisambiguationAuthorProtos.ContributorDescription.Builder, pl.edu.icm.coansys.models.DisambiguationAuthorProtos.ContributorDescriptionOrBuilder> contributorDescriptionBuilder_;
      
      public java.util.List<pl.edu.icm.coansys.models.DisambiguationAuthorProtos.ContributorDescription> getContributorDescriptionList() {
        if (contributorDescriptionBuilder_ == null) {
          return java.util.Collections.unmodifiableList(contributorDescription_);
        } else {
          return contributorDescriptionBuilder_.getMessageList();
        }
      }
      public int getContributorDescriptionCount() {
        if (contributorDescriptionBuilder_ == null) {
          return contributorDescription_.size();
        } else {
          return contributorDescriptionBuilder_.getCount();
        }
      }
      public pl.edu.icm.coansys.models.DisambiguationAuthorProtos.ContributorDescription getContributorDescription(int index) {
        if (contributorDescriptionBuilder_ == null) {
          return contributorDescription_.get(index);
        } else {
          return contributorDescriptionBuilder_.getMessage(index);
        }
      }
      public Builder setContributorDescription(
          int index, pl.edu.icm.coansys.models.DisambiguationAuthorProtos.ContributorDescription value) {
        if (contributorDescriptionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureContributorDescriptionIsMutable();
          contributorDescription_.set(index, value);
          onChanged();
        } else {
          contributorDescriptionBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setContributorDescription(
          int index, pl.edu.icm.coansys.models.DisambiguationAuthorProtos.ContributorDescription.Builder builderForValue) {
        if (contributorDescriptionBuilder_ == null) {
          ensureContributorDescriptionIsMutable();
          contributorDescription_.set(index, builderForValue.build());
          onChanged();
        } else {
          contributorDescriptionBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addContributorDescription(pl.edu.icm.coansys.models.DisambiguationAuthorProtos.ContributorDescription value) {
        if (contributorDescriptionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureContributorDescriptionIsMutable();
          contributorDescription_.add(value);
          onChanged();
        } else {
          contributorDescriptionBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addContributorDescription(
          int index, pl.edu.icm.coansys.models.DisambiguationAuthorProtos.ContributorDescription value) {
        if (contributorDescriptionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureContributorDescriptionIsMutable();
          contributorDescription_.add(index, value);
          onChanged();
        } else {
          contributorDescriptionBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addContributorDescription(
          pl.edu.icm.coansys.models.DisambiguationAuthorProtos.ContributorDescription.Builder builderForValue) {
        if (contributorDescriptionBuilder_ == null) {
          ensureContributorDescriptionIsMutable();
          contributorDescription_.add(builderForValue.build());
          onChanged();
        } else {
          contributorDescriptionBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addContributorDescription(
          int index, pl.edu.icm.coansys.models.DisambiguationAuthorProtos.ContributorDescription.Builder builderForValue) {
        if (contributorDescriptionBuilder_ == null) {
          ensureContributorDescriptionIsMutable();
          contributorDescription_.add(index, builderForValue.build());
          onChanged();
        } else {
          contributorDescriptionBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllContributorDescription(
          java.lang.Iterable<? extends pl.edu.icm.coansys.models.DisambiguationAuthorProtos.ContributorDescription> values) {
        if (contributorDescriptionBuilder_ == null) {
          ensureContributorDescriptionIsMutable();
          super.addAll(values, contributorDescription_);
          onChanged();
        } else {
          contributorDescriptionBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearContributorDescription() {
        if (contributorDescriptionBuilder_ == null) {
          contributorDescription_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          contributorDescriptionBuilder_.clear();
        }
        return this;
      }
      public Builder removeContributorDescription(int index) {
        if (contributorDescriptionBuilder_ == null) {
          ensureContributorDescriptionIsMutable();
          contributorDescription_.remove(index);
          onChanged();
        } else {
          contributorDescriptionBuilder_.remove(index);
        }
        return this;
      }
      public pl.edu.icm.coansys.models.DisambiguationAuthorProtos.ContributorDescription.Builder getContributorDescriptionBuilder(
          int index) {
        return getContributorDescriptionFieldBuilder().getBuilder(index);
      }
      public pl.edu.icm.coansys.models.DisambiguationAuthorProtos.ContributorDescriptionOrBuilder getContributorDescriptionOrBuilder(
          int index) {
        if (contributorDescriptionBuilder_ == null) {
          return contributorDescription_.get(index);  } else {
          return contributorDescriptionBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends pl.edu.icm.coansys.models.DisambiguationAuthorProtos.ContributorDescriptionOrBuilder> 
           getContributorDescriptionOrBuilderList() {
        if (contributorDescriptionBuilder_ != null) {
          return contributorDescriptionBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(contributorDescription_);
        }
      }
      public pl.edu.icm.coansys.models.DisambiguationAuthorProtos.ContributorDescription.Builder addContributorDescriptionBuilder() {
        return getContributorDescriptionFieldBuilder().addBuilder(
            pl.edu.icm.coansys.models.DisambiguationAuthorProtos.ContributorDescription.getDefaultInstance());
      }
      public pl.edu.icm.coansys.models.DisambiguationAuthorProtos.ContributorDescription.Builder addContributorDescriptionBuilder(
          int index) {
        return getContributorDescriptionFieldBuilder().addBuilder(
            index, pl.edu.icm.coansys.models.DisambiguationAuthorProtos.ContributorDescription.getDefaultInstance());
      }
      public java.util.List<pl.edu.icm.coansys.models.DisambiguationAuthorProtos.ContributorDescription.Builder> 
           getContributorDescriptionBuilderList() {
        return getContributorDescriptionFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          pl.edu.icm.coansys.models.DisambiguationAuthorProtos.ContributorDescription, pl.edu.icm.coansys.models.DisambiguationAuthorProtos.ContributorDescription.Builder, pl.edu.icm.coansys.models.DisambiguationAuthorProtos.ContributorDescriptionOrBuilder> 
          getContributorDescriptionFieldBuilder() {
        if (contributorDescriptionBuilder_ == null) {
          contributorDescriptionBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              pl.edu.icm.coansys.models.DisambiguationAuthorProtos.ContributorDescription, pl.edu.icm.coansys.models.DisambiguationAuthorProtos.ContributorDescription.Builder, pl.edu.icm.coansys.models.DisambiguationAuthorProtos.ContributorDescriptionOrBuilder>(
                  contributorDescription_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          contributorDescription_ = null;
        }
        return contributorDescriptionBuilder_;
      }
      
      // repeated .pl.edu.icm.coansys.models.Auxiliar auxs = 3;
      private java.util.List<pl.edu.icm.coansys.models.DisambiguationAuthorProtos.Auxiliar> auxs_ =
        java.util.Collections.emptyList();
      private void ensureAuxsIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          auxs_ = new java.util.ArrayList<pl.edu.icm.coansys.models.DisambiguationAuthorProtos.Auxiliar>(auxs_);
          bitField0_ |= 0x00000004;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          pl.edu.icm.coansys.models.DisambiguationAuthorProtos.Auxiliar, pl.edu.icm.coansys.models.DisambiguationAuthorProtos.Auxiliar.Builder, pl.edu.icm.coansys.models.DisambiguationAuthorProtos.AuxiliarOrBuilder> auxsBuilder_;
      
      public java.util.List<pl.edu.icm.coansys.models.DisambiguationAuthorProtos.Auxiliar> getAuxsList() {
        if (auxsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(auxs_);
        } else {
          return auxsBuilder_.getMessageList();
        }
      }
      public int getAuxsCount() {
        if (auxsBuilder_ == null) {
          return auxs_.size();
        } else {
          return auxsBuilder_.getCount();
        }
      }
      public pl.edu.icm.coansys.models.DisambiguationAuthorProtos.Auxiliar getAuxs(int index) {
        if (auxsBuilder_ == null) {
          return auxs_.get(index);
        } else {
          return auxsBuilder_.getMessage(index);
        }
      }
      public Builder setAuxs(
          int index, pl.edu.icm.coansys.models.DisambiguationAuthorProtos.Auxiliar value) {
        if (auxsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAuxsIsMutable();
          auxs_.set(index, value);
          onChanged();
        } else {
          auxsBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setAuxs(
          int index, pl.edu.icm.coansys.models.DisambiguationAuthorProtos.Auxiliar.Builder builderForValue) {
        if (auxsBuilder_ == null) {
          ensureAuxsIsMutable();
          auxs_.set(index, builderForValue.build());
          onChanged();
        } else {
          auxsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAuxs(pl.edu.icm.coansys.models.DisambiguationAuthorProtos.Auxiliar value) {
        if (auxsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAuxsIsMutable();
          auxs_.add(value);
          onChanged();
        } else {
          auxsBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addAuxs(
          int index, pl.edu.icm.coansys.models.DisambiguationAuthorProtos.Auxiliar value) {
        if (auxsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAuxsIsMutable();
          auxs_.add(index, value);
          onChanged();
        } else {
          auxsBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addAuxs(
          pl.edu.icm.coansys.models.DisambiguationAuthorProtos.Auxiliar.Builder builderForValue) {
        if (auxsBuilder_ == null) {
          ensureAuxsIsMutable();
          auxs_.add(builderForValue.build());
          onChanged();
        } else {
          auxsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addAuxs(
          int index, pl.edu.icm.coansys.models.DisambiguationAuthorProtos.Auxiliar.Builder builderForValue) {
        if (auxsBuilder_ == null) {
          ensureAuxsIsMutable();
          auxs_.add(index, builderForValue.build());
          onChanged();
        } else {
          auxsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllAuxs(
          java.lang.Iterable<? extends pl.edu.icm.coansys.models.DisambiguationAuthorProtos.Auxiliar> values) {
        if (auxsBuilder_ == null) {
          ensureAuxsIsMutable();
          super.addAll(values, auxs_);
          onChanged();
        } else {
          auxsBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearAuxs() {
        if (auxsBuilder_ == null) {
          auxs_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          auxsBuilder_.clear();
        }
        return this;
      }
      public Builder removeAuxs(int index) {
        if (auxsBuilder_ == null) {
          ensureAuxsIsMutable();
          auxs_.remove(index);
          onChanged();
        } else {
          auxsBuilder_.remove(index);
        }
        return this;
      }
      public pl.edu.icm.coansys.models.DisambiguationAuthorProtos.Auxiliar.Builder getAuxsBuilder(
          int index) {
        return getAuxsFieldBuilder().getBuilder(index);
      }
      public pl.edu.icm.coansys.models.DisambiguationAuthorProtos.AuxiliarOrBuilder getAuxsOrBuilder(
          int index) {
        if (auxsBuilder_ == null) {
          return auxs_.get(index);  } else {
          return auxsBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends pl.edu.icm.coansys.models.DisambiguationAuthorProtos.AuxiliarOrBuilder> 
           getAuxsOrBuilderList() {
        if (auxsBuilder_ != null) {
          return auxsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(auxs_);
        }
      }
      public pl.edu.icm.coansys.models.DisambiguationAuthorProtos.Auxiliar.Builder addAuxsBuilder() {
        return getAuxsFieldBuilder().addBuilder(
            pl.edu.icm.coansys.models.DisambiguationAuthorProtos.Auxiliar.getDefaultInstance());
      }
      public pl.edu.icm.coansys.models.DisambiguationAuthorProtos.Auxiliar.Builder addAuxsBuilder(
          int index) {
        return getAuxsFieldBuilder().addBuilder(
            index, pl.edu.icm.coansys.models.DisambiguationAuthorProtos.Auxiliar.getDefaultInstance());
      }
      public java.util.List<pl.edu.icm.coansys.models.DisambiguationAuthorProtos.Auxiliar.Builder> 
           getAuxsBuilderList() {
        return getAuxsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          pl.edu.icm.coansys.models.DisambiguationAuthorProtos.Auxiliar, pl.edu.icm.coansys.models.DisambiguationAuthorProtos.Auxiliar.Builder, pl.edu.icm.coansys.models.DisambiguationAuthorProtos.AuxiliarOrBuilder> 
          getAuxsFieldBuilder() {
        if (auxsBuilder_ == null) {
          auxsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              pl.edu.icm.coansys.models.DisambiguationAuthorProtos.Auxiliar, pl.edu.icm.coansys.models.DisambiguationAuthorProtos.Auxiliar.Builder, pl.edu.icm.coansys.models.DisambiguationAuthorProtos.AuxiliarOrBuilder>(
                  auxs_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          auxs_ = null;
        }
        return auxsBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:pl.edu.icm.coansys.models.DisambiguationAuthorOut)
    }
    
    static {
      defaultInstance = new DisambiguationAuthorOut(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:pl.edu.icm.coansys.models.DisambiguationAuthorOut)
  }
  
  public interface ContributorDescriptionOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string contribId = 1;
    boolean hasContribId();
    String getContribId();
    
    // required string clusterId = 2;
    boolean hasClusterId();
    String getClusterId();
    
    // repeated .pl.edu.icm.coansys.models.Auxiliar auxs = 3;
    java.util.List<pl.edu.icm.coansys.models.DisambiguationAuthorProtos.Auxiliar> 
        getAuxsList();
    pl.edu.icm.coansys.models.DisambiguationAuthorProtos.Auxiliar getAuxs(int index);
    int getAuxsCount();
    java.util.List<? extends pl.edu.icm.coansys.models.DisambiguationAuthorProtos.AuxiliarOrBuilder> 
        getAuxsOrBuilderList();
    pl.edu.icm.coansys.models.DisambiguationAuthorProtos.AuxiliarOrBuilder getAuxsOrBuilder(
        int index);
  }
  public static final class ContributorDescription extends
      com.google.protobuf.GeneratedMessage
      implements ContributorDescriptionOrBuilder {
    // Use ContributorDescription.newBuilder() to construct.
    private ContributorDescription(Builder builder) {
      super(builder);
    }
    private ContributorDescription(boolean noInit) {}
    
    private static final ContributorDescription defaultInstance;
    public static ContributorDescription getDefaultInstance() {
      return defaultInstance;
    }
    
    public ContributorDescription getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pl.edu.icm.coansys.models.DisambiguationAuthorProtos.internal_static_pl_edu_icm_coansys_models_ContributorDescription_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pl.edu.icm.coansys.models.DisambiguationAuthorProtos.internal_static_pl_edu_icm_coansys_models_ContributorDescription_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string contribId = 1;
    public static final int CONTRIBID_FIELD_NUMBER = 1;
    private java.lang.Object contribId_;
    public boolean hasContribId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getContribId() {
      java.lang.Object ref = contribId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          contribId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getContribIdBytes() {
      java.lang.Object ref = contribId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        contribId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string clusterId = 2;
    public static final int CLUSTERID_FIELD_NUMBER = 2;
    private java.lang.Object clusterId_;
    public boolean hasClusterId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getClusterId() {
      java.lang.Object ref = clusterId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          clusterId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getClusterIdBytes() {
      java.lang.Object ref = clusterId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        clusterId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated .pl.edu.icm.coansys.models.Auxiliar auxs = 3;
    public static final int AUXS_FIELD_NUMBER = 3;
    private java.util.List<pl.edu.icm.coansys.models.DisambiguationAuthorProtos.Auxiliar> auxs_;
    public java.util.List<pl.edu.icm.coansys.models.DisambiguationAuthorProtos.Auxiliar> getAuxsList() {
      return auxs_;
    }
    public java.util.List<? extends pl.edu.icm.coansys.models.DisambiguationAuthorProtos.AuxiliarOrBuilder> 
        getAuxsOrBuilderList() {
      return auxs_;
    }
    public int getAuxsCount() {
      return auxs_.size();
    }
    public pl.edu.icm.coansys.models.DisambiguationAuthorProtos.Auxiliar getAuxs(int index) {
      return auxs_.get(index);
    }
    public pl.edu.icm.coansys.models.DisambiguationAuthorProtos.AuxiliarOrBuilder getAuxsOrBuilder(
        int index) {
      return auxs_.get(index);
    }
    
    private void initFields() {
      contribId_ = "";
      clusterId_ = "";
      auxs_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasContribId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasClusterId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getContribIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getClusterIdBytes());
      }
      for (int i = 0; i < auxs_.size(); i++) {
        output.writeMessage(3, auxs_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getContribIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getClusterIdBytes());
      }
      for (int i = 0; i < auxs_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, auxs_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static pl.edu.icm.coansys.models.DisambiguationAuthorProtos.ContributorDescription parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static pl.edu.icm.coansys.models.DisambiguationAuthorProtos.ContributorDescription parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static pl.edu.icm.coansys.models.DisambiguationAuthorProtos.ContributorDescription parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static pl.edu.icm.coansys.models.DisambiguationAuthorProtos.ContributorDescription parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static pl.edu.icm.coansys.models.DisambiguationAuthorProtos.ContributorDescription parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static pl.edu.icm.coansys.models.DisambiguationAuthorProtos.ContributorDescription parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static pl.edu.icm.coansys.models.DisambiguationAuthorProtos.ContributorDescription parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static pl.edu.icm.coansys.models.DisambiguationAuthorProtos.ContributorDescription parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static pl.edu.icm.coansys.models.DisambiguationAuthorProtos.ContributorDescription parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static pl.edu.icm.coansys.models.DisambiguationAuthorProtos.ContributorDescription parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(pl.edu.icm.coansys.models.DisambiguationAuthorProtos.ContributorDescription prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements pl.edu.icm.coansys.models.DisambiguationAuthorProtos.ContributorDescriptionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pl.edu.icm.coansys.models.DisambiguationAuthorProtos.internal_static_pl_edu_icm_coansys_models_ContributorDescription_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pl.edu.icm.coansys.models.DisambiguationAuthorProtos.internal_static_pl_edu_icm_coansys_models_ContributorDescription_fieldAccessorTable;
      }
      
      // Construct using pl.edu.icm.coansys.models.DisambiguationAuthorProtos.ContributorDescription.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getAuxsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        contribId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        clusterId_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        if (auxsBuilder_ == null) {
          auxs_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          auxsBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pl.edu.icm.coansys.models.DisambiguationAuthorProtos.ContributorDescription.getDescriptor();
      }
      
      public pl.edu.icm.coansys.models.DisambiguationAuthorProtos.ContributorDescription getDefaultInstanceForType() {
        return pl.edu.icm.coansys.models.DisambiguationAuthorProtos.ContributorDescription.getDefaultInstance();
      }
      
      public pl.edu.icm.coansys.models.DisambiguationAuthorProtos.ContributorDescription build() {
        pl.edu.icm.coansys.models.DisambiguationAuthorProtos.ContributorDescription result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private pl.edu.icm.coansys.models.DisambiguationAuthorProtos.ContributorDescription buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        pl.edu.icm.coansys.models.DisambiguationAuthorProtos.ContributorDescription result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public pl.edu.icm.coansys.models.DisambiguationAuthorProtos.ContributorDescription buildPartial() {
        pl.edu.icm.coansys.models.DisambiguationAuthorProtos.ContributorDescription result = new pl.edu.icm.coansys.models.DisambiguationAuthorProtos.ContributorDescription(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.contribId_ = contribId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.clusterId_ = clusterId_;
        if (auxsBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            auxs_ = java.util.Collections.unmodifiableList(auxs_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.auxs_ = auxs_;
        } else {
          result.auxs_ = auxsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pl.edu.icm.coansys.models.DisambiguationAuthorProtos.ContributorDescription) {
          return mergeFrom((pl.edu.icm.coansys.models.DisambiguationAuthorProtos.ContributorDescription)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(pl.edu.icm.coansys.models.DisambiguationAuthorProtos.ContributorDescription other) {
        if (other == pl.edu.icm.coansys.models.DisambiguationAuthorProtos.ContributorDescription.getDefaultInstance()) return this;
        if (other.hasContribId()) {
          setContribId(other.getContribId());
        }
        if (other.hasClusterId()) {
          setClusterId(other.getClusterId());
        }
        if (auxsBuilder_ == null) {
          if (!other.auxs_.isEmpty()) {
            if (auxs_.isEmpty()) {
              auxs_ = other.auxs_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureAuxsIsMutable();
              auxs_.addAll(other.auxs_);
            }
            onChanged();
          }
        } else {
          if (!other.auxs_.isEmpty()) {
            if (auxsBuilder_.isEmpty()) {
              auxsBuilder_.dispose();
              auxsBuilder_ = null;
              auxs_ = other.auxs_;
              bitField0_ = (bitField0_ & ~0x00000004);
              auxsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getAuxsFieldBuilder() : null;
            } else {
              auxsBuilder_.addAllMessages(other.auxs_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasContribId()) {
          
          return false;
        }
        if (!hasClusterId()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              contribId_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              clusterId_ = input.readBytes();
              break;
            }
            case 26: {
              pl.edu.icm.coansys.models.DisambiguationAuthorProtos.Auxiliar.Builder subBuilder = pl.edu.icm.coansys.models.DisambiguationAuthorProtos.Auxiliar.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addAuxs(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string contribId = 1;
      private java.lang.Object contribId_ = "";
      public boolean hasContribId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getContribId() {
        java.lang.Object ref = contribId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          contribId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setContribId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        contribId_ = value;
        onChanged();
        return this;
      }
      public Builder clearContribId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        contribId_ = getDefaultInstance().getContribId();
        onChanged();
        return this;
      }
      void setContribId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        contribId_ = value;
        onChanged();
      }
      
      // required string clusterId = 2;
      private java.lang.Object clusterId_ = "";
      public boolean hasClusterId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getClusterId() {
        java.lang.Object ref = clusterId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          clusterId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setClusterId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        clusterId_ = value;
        onChanged();
        return this;
      }
      public Builder clearClusterId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        clusterId_ = getDefaultInstance().getClusterId();
        onChanged();
        return this;
      }
      void setClusterId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        clusterId_ = value;
        onChanged();
      }
      
      // repeated .pl.edu.icm.coansys.models.Auxiliar auxs = 3;
      private java.util.List<pl.edu.icm.coansys.models.DisambiguationAuthorProtos.Auxiliar> auxs_ =
        java.util.Collections.emptyList();
      private void ensureAuxsIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          auxs_ = new java.util.ArrayList<pl.edu.icm.coansys.models.DisambiguationAuthorProtos.Auxiliar>(auxs_);
          bitField0_ |= 0x00000004;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          pl.edu.icm.coansys.models.DisambiguationAuthorProtos.Auxiliar, pl.edu.icm.coansys.models.DisambiguationAuthorProtos.Auxiliar.Builder, pl.edu.icm.coansys.models.DisambiguationAuthorProtos.AuxiliarOrBuilder> auxsBuilder_;
      
      public java.util.List<pl.edu.icm.coansys.models.DisambiguationAuthorProtos.Auxiliar> getAuxsList() {
        if (auxsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(auxs_);
        } else {
          return auxsBuilder_.getMessageList();
        }
      }
      public int getAuxsCount() {
        if (auxsBuilder_ == null) {
          return auxs_.size();
        } else {
          return auxsBuilder_.getCount();
        }
      }
      public pl.edu.icm.coansys.models.DisambiguationAuthorProtos.Auxiliar getAuxs(int index) {
        if (auxsBuilder_ == null) {
          return auxs_.get(index);
        } else {
          return auxsBuilder_.getMessage(index);
        }
      }
      public Builder setAuxs(
          int index, pl.edu.icm.coansys.models.DisambiguationAuthorProtos.Auxiliar value) {
        if (auxsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAuxsIsMutable();
          auxs_.set(index, value);
          onChanged();
        } else {
          auxsBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setAuxs(
          int index, pl.edu.icm.coansys.models.DisambiguationAuthorProtos.Auxiliar.Builder builderForValue) {
        if (auxsBuilder_ == null) {
          ensureAuxsIsMutable();
          auxs_.set(index, builderForValue.build());
          onChanged();
        } else {
          auxsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAuxs(pl.edu.icm.coansys.models.DisambiguationAuthorProtos.Auxiliar value) {
        if (auxsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAuxsIsMutable();
          auxs_.add(value);
          onChanged();
        } else {
          auxsBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addAuxs(
          int index, pl.edu.icm.coansys.models.DisambiguationAuthorProtos.Auxiliar value) {
        if (auxsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAuxsIsMutable();
          auxs_.add(index, value);
          onChanged();
        } else {
          auxsBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addAuxs(
          pl.edu.icm.coansys.models.DisambiguationAuthorProtos.Auxiliar.Builder builderForValue) {
        if (auxsBuilder_ == null) {
          ensureAuxsIsMutable();
          auxs_.add(builderForValue.build());
          onChanged();
        } else {
          auxsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addAuxs(
          int index, pl.edu.icm.coansys.models.DisambiguationAuthorProtos.Auxiliar.Builder builderForValue) {
        if (auxsBuilder_ == null) {
          ensureAuxsIsMutable();
          auxs_.add(index, builderForValue.build());
          onChanged();
        } else {
          auxsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllAuxs(
          java.lang.Iterable<? extends pl.edu.icm.coansys.models.DisambiguationAuthorProtos.Auxiliar> values) {
        if (auxsBuilder_ == null) {
          ensureAuxsIsMutable();
          super.addAll(values, auxs_);
          onChanged();
        } else {
          auxsBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearAuxs() {
        if (auxsBuilder_ == null) {
          auxs_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          auxsBuilder_.clear();
        }
        return this;
      }
      public Builder removeAuxs(int index) {
        if (auxsBuilder_ == null) {
          ensureAuxsIsMutable();
          auxs_.remove(index);
          onChanged();
        } else {
          auxsBuilder_.remove(index);
        }
        return this;
      }
      public pl.edu.icm.coansys.models.DisambiguationAuthorProtos.Auxiliar.Builder getAuxsBuilder(
          int index) {
        return getAuxsFieldBuilder().getBuilder(index);
      }
      public pl.edu.icm.coansys.models.DisambiguationAuthorProtos.AuxiliarOrBuilder getAuxsOrBuilder(
          int index) {
        if (auxsBuilder_ == null) {
          return auxs_.get(index);  } else {
          return auxsBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends pl.edu.icm.coansys.models.DisambiguationAuthorProtos.AuxiliarOrBuilder> 
           getAuxsOrBuilderList() {
        if (auxsBuilder_ != null) {
          return auxsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(auxs_);
        }
      }
      public pl.edu.icm.coansys.models.DisambiguationAuthorProtos.Auxiliar.Builder addAuxsBuilder() {
        return getAuxsFieldBuilder().addBuilder(
            pl.edu.icm.coansys.models.DisambiguationAuthorProtos.Auxiliar.getDefaultInstance());
      }
      public pl.edu.icm.coansys.models.DisambiguationAuthorProtos.Auxiliar.Builder addAuxsBuilder(
          int index) {
        return getAuxsFieldBuilder().addBuilder(
            index, pl.edu.icm.coansys.models.DisambiguationAuthorProtos.Auxiliar.getDefaultInstance());
      }
      public java.util.List<pl.edu.icm.coansys.models.DisambiguationAuthorProtos.Auxiliar.Builder> 
           getAuxsBuilderList() {
        return getAuxsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          pl.edu.icm.coansys.models.DisambiguationAuthorProtos.Auxiliar, pl.edu.icm.coansys.models.DisambiguationAuthorProtos.Auxiliar.Builder, pl.edu.icm.coansys.models.DisambiguationAuthorProtos.AuxiliarOrBuilder> 
          getAuxsFieldBuilder() {
        if (auxsBuilder_ == null) {
          auxsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              pl.edu.icm.coansys.models.DisambiguationAuthorProtos.Auxiliar, pl.edu.icm.coansys.models.DisambiguationAuthorProtos.Auxiliar.Builder, pl.edu.icm.coansys.models.DisambiguationAuthorProtos.AuxiliarOrBuilder>(
                  auxs_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          auxs_ = null;
        }
        return auxsBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:pl.edu.icm.coansys.models.ContributorDescription)
    }
    
    static {
      defaultInstance = new ContributorDescription(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:pl.edu.icm.coansys.models.ContributorDescription)
  }
  
  public interface AuxiliarOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional string type = 1;
    boolean hasType();
    String getType();
    
    // optional string value = 2;
    boolean hasValue();
    String getValue();
  }
  public static final class Auxiliar extends
      com.google.protobuf.GeneratedMessage
      implements AuxiliarOrBuilder {
    // Use Auxiliar.newBuilder() to construct.
    private Auxiliar(Builder builder) {
      super(builder);
    }
    private Auxiliar(boolean noInit) {}
    
    private static final Auxiliar defaultInstance;
    public static Auxiliar getDefaultInstance() {
      return defaultInstance;
    }
    
    public Auxiliar getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pl.edu.icm.coansys.models.DisambiguationAuthorProtos.internal_static_pl_edu_icm_coansys_models_Auxiliar_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pl.edu.icm.coansys.models.DisambiguationAuthorProtos.internal_static_pl_edu_icm_coansys_models_Auxiliar_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional string type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private java.lang.Object type_;
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          type_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string value = 2;
    public static final int VALUE_FIELD_NUMBER = 2;
    private java.lang.Object value_;
    public boolean hasValue() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getValue() {
      java.lang.Object ref = value_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          value_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      type_ = "";
      value_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getTypeBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getValueBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getTypeBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getValueBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static pl.edu.icm.coansys.models.DisambiguationAuthorProtos.Auxiliar parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static pl.edu.icm.coansys.models.DisambiguationAuthorProtos.Auxiliar parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static pl.edu.icm.coansys.models.DisambiguationAuthorProtos.Auxiliar parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static pl.edu.icm.coansys.models.DisambiguationAuthorProtos.Auxiliar parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static pl.edu.icm.coansys.models.DisambiguationAuthorProtos.Auxiliar parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static pl.edu.icm.coansys.models.DisambiguationAuthorProtos.Auxiliar parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static pl.edu.icm.coansys.models.DisambiguationAuthorProtos.Auxiliar parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static pl.edu.icm.coansys.models.DisambiguationAuthorProtos.Auxiliar parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static pl.edu.icm.coansys.models.DisambiguationAuthorProtos.Auxiliar parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static pl.edu.icm.coansys.models.DisambiguationAuthorProtos.Auxiliar parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(pl.edu.icm.coansys.models.DisambiguationAuthorProtos.Auxiliar prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements pl.edu.icm.coansys.models.DisambiguationAuthorProtos.AuxiliarOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pl.edu.icm.coansys.models.DisambiguationAuthorProtos.internal_static_pl_edu_icm_coansys_models_Auxiliar_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pl.edu.icm.coansys.models.DisambiguationAuthorProtos.internal_static_pl_edu_icm_coansys_models_Auxiliar_fieldAccessorTable;
      }
      
      // Construct using pl.edu.icm.coansys.models.DisambiguationAuthorProtos.Auxiliar.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        type_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        value_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pl.edu.icm.coansys.models.DisambiguationAuthorProtos.Auxiliar.getDescriptor();
      }
      
      public pl.edu.icm.coansys.models.DisambiguationAuthorProtos.Auxiliar getDefaultInstanceForType() {
        return pl.edu.icm.coansys.models.DisambiguationAuthorProtos.Auxiliar.getDefaultInstance();
      }
      
      public pl.edu.icm.coansys.models.DisambiguationAuthorProtos.Auxiliar build() {
        pl.edu.icm.coansys.models.DisambiguationAuthorProtos.Auxiliar result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private pl.edu.icm.coansys.models.DisambiguationAuthorProtos.Auxiliar buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        pl.edu.icm.coansys.models.DisambiguationAuthorProtos.Auxiliar result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public pl.edu.icm.coansys.models.DisambiguationAuthorProtos.Auxiliar buildPartial() {
        pl.edu.icm.coansys.models.DisambiguationAuthorProtos.Auxiliar result = new pl.edu.icm.coansys.models.DisambiguationAuthorProtos.Auxiliar(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.value_ = value_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pl.edu.icm.coansys.models.DisambiguationAuthorProtos.Auxiliar) {
          return mergeFrom((pl.edu.icm.coansys.models.DisambiguationAuthorProtos.Auxiliar)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(pl.edu.icm.coansys.models.DisambiguationAuthorProtos.Auxiliar other) {
        if (other == pl.edu.icm.coansys.models.DisambiguationAuthorProtos.Auxiliar.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasValue()) {
          setValue(other.getValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              type_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              value_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string type = 1;
      private java.lang.Object type_ = "";
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          type_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setType(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      void setType(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
      }
      
      // optional string value = 2;
      private java.lang.Object value_ = "";
      public boolean hasValue() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getValue() {
        java.lang.Object ref = value_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          value_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setValue(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        value_ = value;
        onChanged();
        return this;
      }
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000002);
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      void setValue(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        value_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:pl.edu.icm.coansys.models.Auxiliar)
    }
    
    static {
      defaultInstance = new Auxiliar(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:pl.edu.icm.coansys.models.Auxiliar)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_pl_edu_icm_coansys_models_DisambiguationAuthorOut_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_pl_edu_icm_coansys_models_DisambiguationAuthorOut_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_pl_edu_icm_coansys_models_ContributorDescription_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_pl_edu_icm_coansys_models_ContributorDescription_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_pl_edu_icm_coansys_models_Auxiliar_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_pl_edu_icm_coansys_models_Auxiliar_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027disambig_auth_out.proto\022\031pl.edu.icm.co" +
      "ansys.models\"\256\001\n\027DisambiguationAuthorOut" +
      "\022\r\n\005docId\030\001 \002(\t\022Q\n\026contributorDescriptio" +
      "n\030\002 \003(\01321.pl.edu.icm.coansys.models.Cont" +
      "ributorDescription\0221\n\004auxs\030\003 \003(\0132#.pl.ed" +
      "u.icm.coansys.models.Auxiliar\"q\n\026Contrib" +
      "utorDescription\022\021\n\tcontribId\030\001 \002(\t\022\021\n\tcl" +
      "usterId\030\002 \002(\t\0221\n\004auxs\030\003 \003(\0132#.pl.edu.icm" +
      ".coansys.models.Auxiliar\"\'\n\010Auxiliar\022\014\n\004" +
      "type\030\001 \001(\t\022\r\n\005value\030\002 \001(\tB7\n\031pl.edu.icm.",
      "coansys.modelsB\032DisambiguationAuthorProt" +
      "os"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_pl_edu_icm_coansys_models_DisambiguationAuthorOut_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_pl_edu_icm_coansys_models_DisambiguationAuthorOut_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_pl_edu_icm_coansys_models_DisambiguationAuthorOut_descriptor,
              new java.lang.String[] { "DocId", "ContributorDescription", "Auxs", },
              pl.edu.icm.coansys.models.DisambiguationAuthorProtos.DisambiguationAuthorOut.class,
              pl.edu.icm.coansys.models.DisambiguationAuthorProtos.DisambiguationAuthorOut.Builder.class);
          internal_static_pl_edu_icm_coansys_models_ContributorDescription_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_pl_edu_icm_coansys_models_ContributorDescription_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_pl_edu_icm_coansys_models_ContributorDescription_descriptor,
              new java.lang.String[] { "ContribId", "ClusterId", "Auxs", },
              pl.edu.icm.coansys.models.DisambiguationAuthorProtos.ContributorDescription.class,
              pl.edu.icm.coansys.models.DisambiguationAuthorProtos.ContributorDescription.Builder.class);
          internal_static_pl_edu_icm_coansys_models_Auxiliar_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_pl_edu_icm_coansys_models_Auxiliar_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_pl_edu_icm_coansys_models_Auxiliar_descriptor,
              new java.lang.String[] { "Type", "Value", },
              pl.edu.icm.coansys.models.DisambiguationAuthorProtos.Auxiliar.class,
              pl.edu.icm.coansys.models.DisambiguationAuthorProtos.Auxiliar.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
