/*
 * This file is part of CoAnSys project.
 * Copyright (c) 2012-2015 ICM-UW
 * 
 * CoAnSys is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.

 * CoAnSys is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with CoAnSys. If not, see <http://www.gnu.org/licenses/>.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: parent.proto

package pl.edu.icm.coansys.models;

public final class ParentModelProtos {
  private ParentModelProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ParentDisambiguationOutOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string docId = 1;
    /**
     * <code>required string docId = 1;</code>
     */
    boolean hasDocId();
    /**
     * <code>required string docId = 1;</code>
     */
    java.lang.String getDocId();
    /**
     * <code>required string docId = 1;</code>
     */
    com.google.protobuf.ByteString
        getDocIdBytes();

    // required string parentId = 2;
    /**
     * <code>required string parentId = 2;</code>
     */
    boolean hasParentId();
    /**
     * <code>required string parentId = 2;</code>
     */
    java.lang.String getParentId();
    /**
     * <code>required string parentId = 2;</code>
     */
    com.google.protobuf.ByteString
        getParentIdBytes();

    // repeated string parentName = 3;
    /**
     * <code>repeated string parentName = 3;</code>
     */
    java.util.List<java.lang.String>
    getParentNameList();
    /**
     * <code>repeated string parentName = 3;</code>
     */
    int getParentNameCount();
    /**
     * <code>repeated string parentName = 3;</code>
     */
    java.lang.String getParentName(int index);
    /**
     * <code>repeated string parentName = 3;</code>
     */
    com.google.protobuf.ByteString
        getParentNameBytes(int index);

    // repeated .pl.edu.icm.coansys.models.Auxiliar auxs = 4;
    /**
     * <code>repeated .pl.edu.icm.coansys.models.Auxiliar auxs = 4;</code>
     */
    java.util.List<pl.edu.icm.coansys.models.ParentModelProtos.Auxiliar> 
        getAuxsList();
    /**
     * <code>repeated .pl.edu.icm.coansys.models.Auxiliar auxs = 4;</code>
     */
    pl.edu.icm.coansys.models.ParentModelProtos.Auxiliar getAuxs(int index);
    /**
     * <code>repeated .pl.edu.icm.coansys.models.Auxiliar auxs = 4;</code>
     */
    int getAuxsCount();
    /**
     * <code>repeated .pl.edu.icm.coansys.models.Auxiliar auxs = 4;</code>
     */
    java.util.List<? extends pl.edu.icm.coansys.models.ParentModelProtos.AuxiliarOrBuilder> 
        getAuxsOrBuilderList();
    /**
     * <code>repeated .pl.edu.icm.coansys.models.Auxiliar auxs = 4;</code>
     */
    pl.edu.icm.coansys.models.ParentModelProtos.AuxiliarOrBuilder getAuxsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code pl.edu.icm.coansys.models.ParentDisambiguationOut}
   */
  public static final class ParentDisambiguationOut extends
      com.google.protobuf.GeneratedMessage
      implements ParentDisambiguationOutOrBuilder {
    // Use ParentDisambiguationOut.newBuilder() to construct.
    private ParentDisambiguationOut(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ParentDisambiguationOut(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ParentDisambiguationOut defaultInstance;
    public static ParentDisambiguationOut getDefaultInstance() {
      return defaultInstance;
    }

    public ParentDisambiguationOut getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ParentDisambiguationOut(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              docId_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              parentId_ = input.readBytes();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                parentName_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000004;
              }
              parentName_.add(input.readBytes());
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                auxs_ = new java.util.ArrayList<pl.edu.icm.coansys.models.ParentModelProtos.Auxiliar>();
                mutable_bitField0_ |= 0x00000008;
              }
              auxs_.add(input.readMessage(pl.edu.icm.coansys.models.ParentModelProtos.Auxiliar.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          parentName_ = new com.google.protobuf.UnmodifiableLazyStringList(parentName_);
        }
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          auxs_ = java.util.Collections.unmodifiableList(auxs_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pl.edu.icm.coansys.models.ParentModelProtos.internal_static_pl_edu_icm_coansys_models_ParentDisambiguationOut_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pl.edu.icm.coansys.models.ParentModelProtos.internal_static_pl_edu_icm_coansys_models_ParentDisambiguationOut_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pl.edu.icm.coansys.models.ParentModelProtos.ParentDisambiguationOut.class, pl.edu.icm.coansys.models.ParentModelProtos.ParentDisambiguationOut.Builder.class);
    }

    public static com.google.protobuf.Parser<ParentDisambiguationOut> PARSER =
        new com.google.protobuf.AbstractParser<ParentDisambiguationOut>() {
      public ParentDisambiguationOut parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ParentDisambiguationOut(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ParentDisambiguationOut> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string docId = 1;
    public static final int DOCID_FIELD_NUMBER = 1;
    private java.lang.Object docId_;
    /**
     * <code>required string docId = 1;</code>
     */
    public boolean hasDocId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string docId = 1;</code>
     */
    public java.lang.String getDocId() {
      java.lang.Object ref = docId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          docId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string docId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDocIdBytes() {
      java.lang.Object ref = docId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        docId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string parentId = 2;
    public static final int PARENTID_FIELD_NUMBER = 2;
    private java.lang.Object parentId_;
    /**
     * <code>required string parentId = 2;</code>
     */
    public boolean hasParentId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string parentId = 2;</code>
     */
    public java.lang.String getParentId() {
      java.lang.Object ref = parentId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          parentId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string parentId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getParentIdBytes() {
      java.lang.Object ref = parentId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        parentId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // repeated string parentName = 3;
    public static final int PARENTNAME_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList parentName_;
    /**
     * <code>repeated string parentName = 3;</code>
     */
    public java.util.List<java.lang.String>
        getParentNameList() {
      return parentName_;
    }
    /**
     * <code>repeated string parentName = 3;</code>
     */
    public int getParentNameCount() {
      return parentName_.size();
    }
    /**
     * <code>repeated string parentName = 3;</code>
     */
    public java.lang.String getParentName(int index) {
      return parentName_.get(index);
    }
    /**
     * <code>repeated string parentName = 3;</code>
     */
    public com.google.protobuf.ByteString
        getParentNameBytes(int index) {
      return parentName_.getByteString(index);
    }

    // repeated .pl.edu.icm.coansys.models.Auxiliar auxs = 4;
    public static final int AUXS_FIELD_NUMBER = 4;
    private java.util.List<pl.edu.icm.coansys.models.ParentModelProtos.Auxiliar> auxs_;
    /**
     * <code>repeated .pl.edu.icm.coansys.models.Auxiliar auxs = 4;</code>
     */
    public java.util.List<pl.edu.icm.coansys.models.ParentModelProtos.Auxiliar> getAuxsList() {
      return auxs_;
    }
    /**
     * <code>repeated .pl.edu.icm.coansys.models.Auxiliar auxs = 4;</code>
     */
    public java.util.List<? extends pl.edu.icm.coansys.models.ParentModelProtos.AuxiliarOrBuilder> 
        getAuxsOrBuilderList() {
      return auxs_;
    }
    /**
     * <code>repeated .pl.edu.icm.coansys.models.Auxiliar auxs = 4;</code>
     */
    public int getAuxsCount() {
      return auxs_.size();
    }
    /**
     * <code>repeated .pl.edu.icm.coansys.models.Auxiliar auxs = 4;</code>
     */
    public pl.edu.icm.coansys.models.ParentModelProtos.Auxiliar getAuxs(int index) {
      return auxs_.get(index);
    }
    /**
     * <code>repeated .pl.edu.icm.coansys.models.Auxiliar auxs = 4;</code>
     */
    public pl.edu.icm.coansys.models.ParentModelProtos.AuxiliarOrBuilder getAuxsOrBuilder(
        int index) {
      return auxs_.get(index);
    }

    private void initFields() {
      docId_ = "";
      parentId_ = "";
      parentName_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      auxs_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasDocId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasParentId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getDocIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getParentIdBytes());
      }
      for (int i = 0; i < parentName_.size(); i++) {
        output.writeBytes(3, parentName_.getByteString(i));
      }
      for (int i = 0; i < auxs_.size(); i++) {
        output.writeMessage(4, auxs_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getDocIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getParentIdBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < parentName_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(parentName_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getParentNameList().size();
      }
      for (int i = 0; i < auxs_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, auxs_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static pl.edu.icm.coansys.models.ParentModelProtos.ParentDisambiguationOut parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pl.edu.icm.coansys.models.ParentModelProtos.ParentDisambiguationOut parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pl.edu.icm.coansys.models.ParentModelProtos.ParentDisambiguationOut parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pl.edu.icm.coansys.models.ParentModelProtos.ParentDisambiguationOut parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pl.edu.icm.coansys.models.ParentModelProtos.ParentDisambiguationOut parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static pl.edu.icm.coansys.models.ParentModelProtos.ParentDisambiguationOut parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static pl.edu.icm.coansys.models.ParentModelProtos.ParentDisambiguationOut parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static pl.edu.icm.coansys.models.ParentModelProtos.ParentDisambiguationOut parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static pl.edu.icm.coansys.models.ParentModelProtos.ParentDisambiguationOut parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static pl.edu.icm.coansys.models.ParentModelProtos.ParentDisambiguationOut parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(pl.edu.icm.coansys.models.ParentModelProtos.ParentDisambiguationOut prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pl.edu.icm.coansys.models.ParentDisambiguationOut}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements pl.edu.icm.coansys.models.ParentModelProtos.ParentDisambiguationOutOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pl.edu.icm.coansys.models.ParentModelProtos.internal_static_pl_edu_icm_coansys_models_ParentDisambiguationOut_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pl.edu.icm.coansys.models.ParentModelProtos.internal_static_pl_edu_icm_coansys_models_ParentDisambiguationOut_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pl.edu.icm.coansys.models.ParentModelProtos.ParentDisambiguationOut.class, pl.edu.icm.coansys.models.ParentModelProtos.ParentDisambiguationOut.Builder.class);
      }

      // Construct using pl.edu.icm.coansys.models.ParentModelProtos.ParentDisambiguationOut.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getAuxsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        docId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        parentId_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        parentName_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        if (auxsBuilder_ == null) {
          auxs_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          auxsBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pl.edu.icm.coansys.models.ParentModelProtos.internal_static_pl_edu_icm_coansys_models_ParentDisambiguationOut_descriptor;
      }

      public pl.edu.icm.coansys.models.ParentModelProtos.ParentDisambiguationOut getDefaultInstanceForType() {
        return pl.edu.icm.coansys.models.ParentModelProtos.ParentDisambiguationOut.getDefaultInstance();
      }

      public pl.edu.icm.coansys.models.ParentModelProtos.ParentDisambiguationOut build() {
        pl.edu.icm.coansys.models.ParentModelProtos.ParentDisambiguationOut result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public pl.edu.icm.coansys.models.ParentModelProtos.ParentDisambiguationOut buildPartial() {
        pl.edu.icm.coansys.models.ParentModelProtos.ParentDisambiguationOut result = new pl.edu.icm.coansys.models.ParentModelProtos.ParentDisambiguationOut(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.docId_ = docId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.parentId_ = parentId_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          parentName_ = new com.google.protobuf.UnmodifiableLazyStringList(
              parentName_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.parentName_ = parentName_;
        if (auxsBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            auxs_ = java.util.Collections.unmodifiableList(auxs_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.auxs_ = auxs_;
        } else {
          result.auxs_ = auxsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pl.edu.icm.coansys.models.ParentModelProtos.ParentDisambiguationOut) {
          return mergeFrom((pl.edu.icm.coansys.models.ParentModelProtos.ParentDisambiguationOut)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pl.edu.icm.coansys.models.ParentModelProtos.ParentDisambiguationOut other) {
        if (other == pl.edu.icm.coansys.models.ParentModelProtos.ParentDisambiguationOut.getDefaultInstance()) return this;
        if (other.hasDocId()) {
          bitField0_ |= 0x00000001;
          docId_ = other.docId_;
          onChanged();
        }
        if (other.hasParentId()) {
          bitField0_ |= 0x00000002;
          parentId_ = other.parentId_;
          onChanged();
        }
        if (!other.parentName_.isEmpty()) {
          if (parentName_.isEmpty()) {
            parentName_ = other.parentName_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureParentNameIsMutable();
            parentName_.addAll(other.parentName_);
          }
          onChanged();
        }
        if (auxsBuilder_ == null) {
          if (!other.auxs_.isEmpty()) {
            if (auxs_.isEmpty()) {
              auxs_ = other.auxs_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureAuxsIsMutable();
              auxs_.addAll(other.auxs_);
            }
            onChanged();
          }
        } else {
          if (!other.auxs_.isEmpty()) {
            if (auxsBuilder_.isEmpty()) {
              auxsBuilder_.dispose();
              auxsBuilder_ = null;
              auxs_ = other.auxs_;
              bitField0_ = (bitField0_ & ~0x00000008);
              auxsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getAuxsFieldBuilder() : null;
            } else {
              auxsBuilder_.addAllMessages(other.auxs_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasDocId()) {
          
          return false;
        }
        if (!hasParentId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pl.edu.icm.coansys.models.ParentModelProtos.ParentDisambiguationOut parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pl.edu.icm.coansys.models.ParentModelProtos.ParentDisambiguationOut) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string docId = 1;
      private java.lang.Object docId_ = "";
      /**
       * <code>required string docId = 1;</code>
       */
      public boolean hasDocId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string docId = 1;</code>
       */
      public java.lang.String getDocId() {
        java.lang.Object ref = docId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          docId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string docId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getDocIdBytes() {
        java.lang.Object ref = docId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          docId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string docId = 1;</code>
       */
      public Builder setDocId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        docId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string docId = 1;</code>
       */
      public Builder clearDocId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        docId_ = getDefaultInstance().getDocId();
        onChanged();
        return this;
      }
      /**
       * <code>required string docId = 1;</code>
       */
      public Builder setDocIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        docId_ = value;
        onChanged();
        return this;
      }

      // required string parentId = 2;
      private java.lang.Object parentId_ = "";
      /**
       * <code>required string parentId = 2;</code>
       */
      public boolean hasParentId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string parentId = 2;</code>
       */
      public java.lang.String getParentId() {
        java.lang.Object ref = parentId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          parentId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string parentId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getParentIdBytes() {
        java.lang.Object ref = parentId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          parentId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string parentId = 2;</code>
       */
      public Builder setParentId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        parentId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string parentId = 2;</code>
       */
      public Builder clearParentId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        parentId_ = getDefaultInstance().getParentId();
        onChanged();
        return this;
      }
      /**
       * <code>required string parentId = 2;</code>
       */
      public Builder setParentIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        parentId_ = value;
        onChanged();
        return this;
      }

      // repeated string parentName = 3;
      private com.google.protobuf.LazyStringList parentName_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureParentNameIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          parentName_ = new com.google.protobuf.LazyStringArrayList(parentName_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated string parentName = 3;</code>
       */
      public java.util.List<java.lang.String>
          getParentNameList() {
        return java.util.Collections.unmodifiableList(parentName_);
      }
      /**
       * <code>repeated string parentName = 3;</code>
       */
      public int getParentNameCount() {
        return parentName_.size();
      }
      /**
       * <code>repeated string parentName = 3;</code>
       */
      public java.lang.String getParentName(int index) {
        return parentName_.get(index);
      }
      /**
       * <code>repeated string parentName = 3;</code>
       */
      public com.google.protobuf.ByteString
          getParentNameBytes(int index) {
        return parentName_.getByteString(index);
      }
      /**
       * <code>repeated string parentName = 3;</code>
       */
      public Builder setParentName(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureParentNameIsMutable();
        parentName_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string parentName = 3;</code>
       */
      public Builder addParentName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureParentNameIsMutable();
        parentName_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string parentName = 3;</code>
       */
      public Builder addAllParentName(
          java.lang.Iterable<java.lang.String> values) {
        ensureParentNameIsMutable();
        super.addAll(values, parentName_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string parentName = 3;</code>
       */
      public Builder clearParentName() {
        parentName_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string parentName = 3;</code>
       */
      public Builder addParentNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureParentNameIsMutable();
        parentName_.add(value);
        onChanged();
        return this;
      }

      // repeated .pl.edu.icm.coansys.models.Auxiliar auxs = 4;
      private java.util.List<pl.edu.icm.coansys.models.ParentModelProtos.Auxiliar> auxs_ =
        java.util.Collections.emptyList();
      private void ensureAuxsIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          auxs_ = new java.util.ArrayList<pl.edu.icm.coansys.models.ParentModelProtos.Auxiliar>(auxs_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          pl.edu.icm.coansys.models.ParentModelProtos.Auxiliar, pl.edu.icm.coansys.models.ParentModelProtos.Auxiliar.Builder, pl.edu.icm.coansys.models.ParentModelProtos.AuxiliarOrBuilder> auxsBuilder_;

      /**
       * <code>repeated .pl.edu.icm.coansys.models.Auxiliar auxs = 4;</code>
       */
      public java.util.List<pl.edu.icm.coansys.models.ParentModelProtos.Auxiliar> getAuxsList() {
        if (auxsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(auxs_);
        } else {
          return auxsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .pl.edu.icm.coansys.models.Auxiliar auxs = 4;</code>
       */
      public int getAuxsCount() {
        if (auxsBuilder_ == null) {
          return auxs_.size();
        } else {
          return auxsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .pl.edu.icm.coansys.models.Auxiliar auxs = 4;</code>
       */
      public pl.edu.icm.coansys.models.ParentModelProtos.Auxiliar getAuxs(int index) {
        if (auxsBuilder_ == null) {
          return auxs_.get(index);
        } else {
          return auxsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .pl.edu.icm.coansys.models.Auxiliar auxs = 4;</code>
       */
      public Builder setAuxs(
          int index, pl.edu.icm.coansys.models.ParentModelProtos.Auxiliar value) {
        if (auxsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAuxsIsMutable();
          auxs_.set(index, value);
          onChanged();
        } else {
          auxsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .pl.edu.icm.coansys.models.Auxiliar auxs = 4;</code>
       */
      public Builder setAuxs(
          int index, pl.edu.icm.coansys.models.ParentModelProtos.Auxiliar.Builder builderForValue) {
        if (auxsBuilder_ == null) {
          ensureAuxsIsMutable();
          auxs_.set(index, builderForValue.build());
          onChanged();
        } else {
          auxsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .pl.edu.icm.coansys.models.Auxiliar auxs = 4;</code>
       */
      public Builder addAuxs(pl.edu.icm.coansys.models.ParentModelProtos.Auxiliar value) {
        if (auxsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAuxsIsMutable();
          auxs_.add(value);
          onChanged();
        } else {
          auxsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .pl.edu.icm.coansys.models.Auxiliar auxs = 4;</code>
       */
      public Builder addAuxs(
          int index, pl.edu.icm.coansys.models.ParentModelProtos.Auxiliar value) {
        if (auxsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAuxsIsMutable();
          auxs_.add(index, value);
          onChanged();
        } else {
          auxsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .pl.edu.icm.coansys.models.Auxiliar auxs = 4;</code>
       */
      public Builder addAuxs(
          pl.edu.icm.coansys.models.ParentModelProtos.Auxiliar.Builder builderForValue) {
        if (auxsBuilder_ == null) {
          ensureAuxsIsMutable();
          auxs_.add(builderForValue.build());
          onChanged();
        } else {
          auxsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .pl.edu.icm.coansys.models.Auxiliar auxs = 4;</code>
       */
      public Builder addAuxs(
          int index, pl.edu.icm.coansys.models.ParentModelProtos.Auxiliar.Builder builderForValue) {
        if (auxsBuilder_ == null) {
          ensureAuxsIsMutable();
          auxs_.add(index, builderForValue.build());
          onChanged();
        } else {
          auxsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .pl.edu.icm.coansys.models.Auxiliar auxs = 4;</code>
       */
      public Builder addAllAuxs(
          java.lang.Iterable<? extends pl.edu.icm.coansys.models.ParentModelProtos.Auxiliar> values) {
        if (auxsBuilder_ == null) {
          ensureAuxsIsMutable();
          super.addAll(values, auxs_);
          onChanged();
        } else {
          auxsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .pl.edu.icm.coansys.models.Auxiliar auxs = 4;</code>
       */
      public Builder clearAuxs() {
        if (auxsBuilder_ == null) {
          auxs_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          auxsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .pl.edu.icm.coansys.models.Auxiliar auxs = 4;</code>
       */
      public Builder removeAuxs(int index) {
        if (auxsBuilder_ == null) {
          ensureAuxsIsMutable();
          auxs_.remove(index);
          onChanged();
        } else {
          auxsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .pl.edu.icm.coansys.models.Auxiliar auxs = 4;</code>
       */
      public pl.edu.icm.coansys.models.ParentModelProtos.Auxiliar.Builder getAuxsBuilder(
          int index) {
        return getAuxsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .pl.edu.icm.coansys.models.Auxiliar auxs = 4;</code>
       */
      public pl.edu.icm.coansys.models.ParentModelProtos.AuxiliarOrBuilder getAuxsOrBuilder(
          int index) {
        if (auxsBuilder_ == null) {
          return auxs_.get(index);  } else {
          return auxsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .pl.edu.icm.coansys.models.Auxiliar auxs = 4;</code>
       */
      public java.util.List<? extends pl.edu.icm.coansys.models.ParentModelProtos.AuxiliarOrBuilder> 
           getAuxsOrBuilderList() {
        if (auxsBuilder_ != null) {
          return auxsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(auxs_);
        }
      }
      /**
       * <code>repeated .pl.edu.icm.coansys.models.Auxiliar auxs = 4;</code>
       */
      public pl.edu.icm.coansys.models.ParentModelProtos.Auxiliar.Builder addAuxsBuilder() {
        return getAuxsFieldBuilder().addBuilder(
            pl.edu.icm.coansys.models.ParentModelProtos.Auxiliar.getDefaultInstance());
      }
      /**
       * <code>repeated .pl.edu.icm.coansys.models.Auxiliar auxs = 4;</code>
       */
      public pl.edu.icm.coansys.models.ParentModelProtos.Auxiliar.Builder addAuxsBuilder(
          int index) {
        return getAuxsFieldBuilder().addBuilder(
            index, pl.edu.icm.coansys.models.ParentModelProtos.Auxiliar.getDefaultInstance());
      }
      /**
       * <code>repeated .pl.edu.icm.coansys.models.Auxiliar auxs = 4;</code>
       */
      public java.util.List<pl.edu.icm.coansys.models.ParentModelProtos.Auxiliar.Builder> 
           getAuxsBuilderList() {
        return getAuxsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          pl.edu.icm.coansys.models.ParentModelProtos.Auxiliar, pl.edu.icm.coansys.models.ParentModelProtos.Auxiliar.Builder, pl.edu.icm.coansys.models.ParentModelProtos.AuxiliarOrBuilder> 
          getAuxsFieldBuilder() {
        if (auxsBuilder_ == null) {
          auxsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              pl.edu.icm.coansys.models.ParentModelProtos.Auxiliar, pl.edu.icm.coansys.models.ParentModelProtos.Auxiliar.Builder, pl.edu.icm.coansys.models.ParentModelProtos.AuxiliarOrBuilder>(
                  auxs_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          auxs_ = null;
        }
        return auxsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:pl.edu.icm.coansys.models.ParentDisambiguationOut)
    }

    static {
      defaultInstance = new ParentDisambiguationOut(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:pl.edu.icm.coansys.models.ParentDisambiguationOut)
  }

  public interface AuxiliarOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string type = 1;
    /**
     * <code>optional string type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>optional string type = 1;</code>
     */
    java.lang.String getType();
    /**
     * <code>optional string type = 1;</code>
     */
    com.google.protobuf.ByteString
        getTypeBytes();

    // optional string value = 2;
    /**
     * <code>optional string value = 2;</code>
     */
    boolean hasValue();
    /**
     * <code>optional string value = 2;</code>
     */
    java.lang.String getValue();
    /**
     * <code>optional string value = 2;</code>
     */
    com.google.protobuf.ByteString
        getValueBytes();
  }
  /**
   * Protobuf type {@code pl.edu.icm.coansys.models.Auxiliar}
   */
  public static final class Auxiliar extends
      com.google.protobuf.GeneratedMessage
      implements AuxiliarOrBuilder {
    // Use Auxiliar.newBuilder() to construct.
    private Auxiliar(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Auxiliar(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Auxiliar defaultInstance;
    public static Auxiliar getDefaultInstance() {
      return defaultInstance;
    }

    public Auxiliar getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Auxiliar(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              type_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              value_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pl.edu.icm.coansys.models.ParentModelProtos.internal_static_pl_edu_icm_coansys_models_Auxiliar_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pl.edu.icm.coansys.models.ParentModelProtos.internal_static_pl_edu_icm_coansys_models_Auxiliar_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pl.edu.icm.coansys.models.ParentModelProtos.Auxiliar.class, pl.edu.icm.coansys.models.ParentModelProtos.Auxiliar.Builder.class);
    }

    public static com.google.protobuf.Parser<Auxiliar> PARSER =
        new com.google.protobuf.AbstractParser<Auxiliar>() {
      public Auxiliar parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Auxiliar(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Auxiliar> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private java.lang.Object type_;
    /**
     * <code>optional string type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string type = 1;</code>
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          type_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string type = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string value = 2;
    public static final int VALUE_FIELD_NUMBER = 2;
    private java.lang.Object value_;
    /**
     * <code>optional string value = 2;</code>
     */
    public boolean hasValue() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string value = 2;</code>
     */
    public java.lang.String getValue() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          value_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string value = 2;</code>
     */
    public com.google.protobuf.ByteString
        getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      type_ = "";
      value_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getTypeBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getValueBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getTypeBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getValueBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static pl.edu.icm.coansys.models.ParentModelProtos.Auxiliar parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pl.edu.icm.coansys.models.ParentModelProtos.Auxiliar parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pl.edu.icm.coansys.models.ParentModelProtos.Auxiliar parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pl.edu.icm.coansys.models.ParentModelProtos.Auxiliar parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pl.edu.icm.coansys.models.ParentModelProtos.Auxiliar parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static pl.edu.icm.coansys.models.ParentModelProtos.Auxiliar parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static pl.edu.icm.coansys.models.ParentModelProtos.Auxiliar parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static pl.edu.icm.coansys.models.ParentModelProtos.Auxiliar parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static pl.edu.icm.coansys.models.ParentModelProtos.Auxiliar parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static pl.edu.icm.coansys.models.ParentModelProtos.Auxiliar parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(pl.edu.icm.coansys.models.ParentModelProtos.Auxiliar prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pl.edu.icm.coansys.models.Auxiliar}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements pl.edu.icm.coansys.models.ParentModelProtos.AuxiliarOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pl.edu.icm.coansys.models.ParentModelProtos.internal_static_pl_edu_icm_coansys_models_Auxiliar_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pl.edu.icm.coansys.models.ParentModelProtos.internal_static_pl_edu_icm_coansys_models_Auxiliar_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pl.edu.icm.coansys.models.ParentModelProtos.Auxiliar.class, pl.edu.icm.coansys.models.ParentModelProtos.Auxiliar.Builder.class);
      }

      // Construct using pl.edu.icm.coansys.models.ParentModelProtos.Auxiliar.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        value_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pl.edu.icm.coansys.models.ParentModelProtos.internal_static_pl_edu_icm_coansys_models_Auxiliar_descriptor;
      }

      public pl.edu.icm.coansys.models.ParentModelProtos.Auxiliar getDefaultInstanceForType() {
        return pl.edu.icm.coansys.models.ParentModelProtos.Auxiliar.getDefaultInstance();
      }

      public pl.edu.icm.coansys.models.ParentModelProtos.Auxiliar build() {
        pl.edu.icm.coansys.models.ParentModelProtos.Auxiliar result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public pl.edu.icm.coansys.models.ParentModelProtos.Auxiliar buildPartial() {
        pl.edu.icm.coansys.models.ParentModelProtos.Auxiliar result = new pl.edu.icm.coansys.models.ParentModelProtos.Auxiliar(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.value_ = value_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pl.edu.icm.coansys.models.ParentModelProtos.Auxiliar) {
          return mergeFrom((pl.edu.icm.coansys.models.ParentModelProtos.Auxiliar)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pl.edu.icm.coansys.models.ParentModelProtos.Auxiliar other) {
        if (other == pl.edu.icm.coansys.models.ParentModelProtos.Auxiliar.getDefaultInstance()) return this;
        if (other.hasType()) {
          bitField0_ |= 0x00000001;
          type_ = other.type_;
          onChanged();
        }
        if (other.hasValue()) {
          bitField0_ |= 0x00000002;
          value_ = other.value_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pl.edu.icm.coansys.models.ParentModelProtos.Auxiliar parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pl.edu.icm.coansys.models.ParentModelProtos.Auxiliar) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string type = 1;
      private java.lang.Object type_ = "";
      /**
       * <code>optional string type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string type = 1;</code>
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          type_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string type = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string type = 1;</code>
       */
      public Builder setType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      /**
       * <code>optional string type = 1;</code>
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }

      // optional string value = 2;
      private java.lang.Object value_ = "";
      /**
       * <code>optional string value = 2;</code>
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string value = 2;</code>
       */
      public java.lang.String getValue() {
        java.lang.Object ref = value_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          value_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string value = 2;</code>
       */
      public com.google.protobuf.ByteString
          getValueBytes() {
        java.lang.Object ref = value_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string value = 2;</code>
       */
      public Builder setValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string value = 2;</code>
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000002);
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      /**
       * <code>optional string value = 2;</code>
       */
      public Builder setValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        value_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:pl.edu.icm.coansys.models.Auxiliar)
    }

    static {
      defaultInstance = new Auxiliar(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:pl.edu.icm.coansys.models.Auxiliar)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_pl_edu_icm_coansys_models_ParentDisambiguationOut_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_pl_edu_icm_coansys_models_ParentDisambiguationOut_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_pl_edu_icm_coansys_models_Auxiliar_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_pl_edu_icm_coansys_models_Auxiliar_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014parent.proto\022\031pl.edu.icm.coansys.model" +
      "s\"\201\001\n\027ParentDisambiguationOut\022\r\n\005docId\030\001" +
      " \002(\t\022\020\n\010parentId\030\002 \002(\t\022\022\n\nparentName\030\003 \003" +
      "(\t\0221\n\004auxs\030\004 \003(\0132#.pl.edu.icm.coansys.mo" +
      "dels.Auxiliar\"\'\n\010Auxiliar\022\014\n\004type\030\001 \001(\t\022" +
      "\r\n\005value\030\002 \001(\tB.\n\031pl.edu.icm.coansys.mod" +
      "elsB\021ParentModelProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_pl_edu_icm_coansys_models_ParentDisambiguationOut_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_pl_edu_icm_coansys_models_ParentDisambiguationOut_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_pl_edu_icm_coansys_models_ParentDisambiguationOut_descriptor,
              new java.lang.String[] { "DocId", "ParentId", "ParentName", "Auxs", });
          internal_static_pl_edu_icm_coansys_models_Auxiliar_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_pl_edu_icm_coansys_models_Auxiliar_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_pl_edu_icm_coansys_models_Auxiliar_descriptor,
              new java.lang.String[] { "Type", "Value", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
