// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person.proto

package pl.edu.icm.coansys.models;

public final class PersonProtos {
  private PersonProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PersonMetadataOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string key = 1;
    boolean hasKey();
    String getKey();
    
    // repeated string name = 2;
    java.util.List<String> getNameList();
    int getNameCount();
    String getName(int index);
    
    // repeated string firstname = 3;
    java.util.List<String> getFirstnameList();
    int getFirstnameCount();
    String getFirstname(int index);
    
    // repeated string lastname = 4;
    java.util.List<String> getLastnameList();
    int getLastnameCount();
    String getLastname(int index);
    
    // repeated string email = 5;
    java.util.List<String> getEmailList();
    int getEmailCount();
    String getEmail(int index);
    
    // repeated .KeyValue otherId = 6;
    java.util.List<pl.edu.icm.coansys.models.DocumentProtos.KeyValue> 
        getOtherIdList();
    pl.edu.icm.coansys.models.DocumentProtos.KeyValue getOtherId(int index);
    int getOtherIdCount();
    java.util.List<? extends pl.edu.icm.coansys.models.DocumentProtos.KeyValueOrBuilder> 
        getOtherIdOrBuilderList();
    pl.edu.icm.coansys.models.DocumentProtos.KeyValueOrBuilder getOtherIdOrBuilder(
        int index);
  }
  public static final class PersonMetadata extends
      com.google.protobuf.GeneratedMessage
      implements PersonMetadataOrBuilder {
    // Use PersonMetadata.newBuilder() to construct.
    private PersonMetadata(Builder builder) {
      super(builder);
    }
    private PersonMetadata(boolean noInit) {}
    
    private static final PersonMetadata defaultInstance;
    public static PersonMetadata getDefaultInstance() {
      return defaultInstance;
    }
    
    public PersonMetadata getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pl.edu.icm.coansys.models.PersonProtos.internal_static_PersonMetadata_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pl.edu.icm.coansys.models.PersonProtos.internal_static_PersonMetadata_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string key = 1;
    public static final int KEY_FIELD_NUMBER = 1;
    private java.lang.Object key_;
    public boolean hasKey() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getKey() {
      java.lang.Object ref = key_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          key_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated string name = 2;
    public static final int NAME_FIELD_NUMBER = 2;
    private com.google.protobuf.LazyStringList name_;
    public java.util.List<String>
        getNameList() {
      return name_;
    }
    public int getNameCount() {
      return name_.size();
    }
    public String getName(int index) {
      return name_.get(index);
    }
    
    // repeated string firstname = 3;
    public static final int FIRSTNAME_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList firstname_;
    public java.util.List<String>
        getFirstnameList() {
      return firstname_;
    }
    public int getFirstnameCount() {
      return firstname_.size();
    }
    public String getFirstname(int index) {
      return firstname_.get(index);
    }
    
    // repeated string lastname = 4;
    public static final int LASTNAME_FIELD_NUMBER = 4;
    private com.google.protobuf.LazyStringList lastname_;
    public java.util.List<String>
        getLastnameList() {
      return lastname_;
    }
    public int getLastnameCount() {
      return lastname_.size();
    }
    public String getLastname(int index) {
      return lastname_.get(index);
    }
    
    // repeated string email = 5;
    public static final int EMAIL_FIELD_NUMBER = 5;
    private com.google.protobuf.LazyStringList email_;
    public java.util.List<String>
        getEmailList() {
      return email_;
    }
    public int getEmailCount() {
      return email_.size();
    }
    public String getEmail(int index) {
      return email_.get(index);
    }
    
    // repeated .KeyValue otherId = 6;
    public static final int OTHERID_FIELD_NUMBER = 6;
    private java.util.List<pl.edu.icm.coansys.models.DocumentProtos.KeyValue> otherId_;
    public java.util.List<pl.edu.icm.coansys.models.DocumentProtos.KeyValue> getOtherIdList() {
      return otherId_;
    }
    public java.util.List<? extends pl.edu.icm.coansys.models.DocumentProtos.KeyValueOrBuilder> 
        getOtherIdOrBuilderList() {
      return otherId_;
    }
    public int getOtherIdCount() {
      return otherId_.size();
    }
    public pl.edu.icm.coansys.models.DocumentProtos.KeyValue getOtherId(int index) {
      return otherId_.get(index);
    }
    public pl.edu.icm.coansys.models.DocumentProtos.KeyValueOrBuilder getOtherIdOrBuilder(
        int index) {
      return otherId_.get(index);
    }
    
    private void initFields() {
      key_ = "";
      name_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      firstname_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      lastname_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      email_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      otherId_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasKey()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getOtherIdCount(); i++) {
        if (!getOtherId(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getKeyBytes());
      }
      for (int i = 0; i < name_.size(); i++) {
        output.writeBytes(2, name_.getByteString(i));
      }
      for (int i = 0; i < firstname_.size(); i++) {
        output.writeBytes(3, firstname_.getByteString(i));
      }
      for (int i = 0; i < lastname_.size(); i++) {
        output.writeBytes(4, lastname_.getByteString(i));
      }
      for (int i = 0; i < email_.size(); i++) {
        output.writeBytes(5, email_.getByteString(i));
      }
      for (int i = 0; i < otherId_.size(); i++) {
        output.writeMessage(6, otherId_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getKeyBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < name_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(name_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getNameList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < firstname_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(firstname_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getFirstnameList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < lastname_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(lastname_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getLastnameList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < email_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(email_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getEmailList().size();
      }
      for (int i = 0; i < otherId_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, otherId_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static pl.edu.icm.coansys.models.PersonProtos.PersonMetadata parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static pl.edu.icm.coansys.models.PersonProtos.PersonMetadata parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static pl.edu.icm.coansys.models.PersonProtos.PersonMetadata parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static pl.edu.icm.coansys.models.PersonProtos.PersonMetadata parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static pl.edu.icm.coansys.models.PersonProtos.PersonMetadata parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static pl.edu.icm.coansys.models.PersonProtos.PersonMetadata parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static pl.edu.icm.coansys.models.PersonProtos.PersonMetadata parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static pl.edu.icm.coansys.models.PersonProtos.PersonMetadata parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static pl.edu.icm.coansys.models.PersonProtos.PersonMetadata parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static pl.edu.icm.coansys.models.PersonProtos.PersonMetadata parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(pl.edu.icm.coansys.models.PersonProtos.PersonMetadata prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements pl.edu.icm.coansys.models.PersonProtos.PersonMetadataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pl.edu.icm.coansys.models.PersonProtos.internal_static_PersonMetadata_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pl.edu.icm.coansys.models.PersonProtos.internal_static_PersonMetadata_fieldAccessorTable;
      }
      
      // Construct using pl.edu.icm.coansys.models.PersonProtos.PersonMetadata.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getOtherIdFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        key_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        firstname_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        lastname_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        email_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        if (otherIdBuilder_ == null) {
          otherId_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000020);
        } else {
          otherIdBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pl.edu.icm.coansys.models.PersonProtos.PersonMetadata.getDescriptor();
      }
      
      public pl.edu.icm.coansys.models.PersonProtos.PersonMetadata getDefaultInstanceForType() {
        return pl.edu.icm.coansys.models.PersonProtos.PersonMetadata.getDefaultInstance();
      }
      
      public pl.edu.icm.coansys.models.PersonProtos.PersonMetadata build() {
        pl.edu.icm.coansys.models.PersonProtos.PersonMetadata result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private pl.edu.icm.coansys.models.PersonProtos.PersonMetadata buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        pl.edu.icm.coansys.models.PersonProtos.PersonMetadata result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public pl.edu.icm.coansys.models.PersonProtos.PersonMetadata buildPartial() {
        pl.edu.icm.coansys.models.PersonProtos.PersonMetadata result = new pl.edu.icm.coansys.models.PersonProtos.PersonMetadata(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.key_ = key_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          name_ = new com.google.protobuf.UnmodifiableLazyStringList(
              name_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.name_ = name_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          firstname_ = new com.google.protobuf.UnmodifiableLazyStringList(
              firstname_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.firstname_ = firstname_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          lastname_ = new com.google.protobuf.UnmodifiableLazyStringList(
              lastname_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.lastname_ = lastname_;
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          email_ = new com.google.protobuf.UnmodifiableLazyStringList(
              email_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.email_ = email_;
        if (otherIdBuilder_ == null) {
          if (((bitField0_ & 0x00000020) == 0x00000020)) {
            otherId_ = java.util.Collections.unmodifiableList(otherId_);
            bitField0_ = (bitField0_ & ~0x00000020);
          }
          result.otherId_ = otherId_;
        } else {
          result.otherId_ = otherIdBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pl.edu.icm.coansys.models.PersonProtos.PersonMetadata) {
          return mergeFrom((pl.edu.icm.coansys.models.PersonProtos.PersonMetadata)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(pl.edu.icm.coansys.models.PersonProtos.PersonMetadata other) {
        if (other == pl.edu.icm.coansys.models.PersonProtos.PersonMetadata.getDefaultInstance()) return this;
        if (other.hasKey()) {
          setKey(other.getKey());
        }
        if (!other.name_.isEmpty()) {
          if (name_.isEmpty()) {
            name_ = other.name_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureNameIsMutable();
            name_.addAll(other.name_);
          }
          onChanged();
        }
        if (!other.firstname_.isEmpty()) {
          if (firstname_.isEmpty()) {
            firstname_ = other.firstname_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureFirstnameIsMutable();
            firstname_.addAll(other.firstname_);
          }
          onChanged();
        }
        if (!other.lastname_.isEmpty()) {
          if (lastname_.isEmpty()) {
            lastname_ = other.lastname_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureLastnameIsMutable();
            lastname_.addAll(other.lastname_);
          }
          onChanged();
        }
        if (!other.email_.isEmpty()) {
          if (email_.isEmpty()) {
            email_ = other.email_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureEmailIsMutable();
            email_.addAll(other.email_);
          }
          onChanged();
        }
        if (otherIdBuilder_ == null) {
          if (!other.otherId_.isEmpty()) {
            if (otherId_.isEmpty()) {
              otherId_ = other.otherId_;
              bitField0_ = (bitField0_ & ~0x00000020);
            } else {
              ensureOtherIdIsMutable();
              otherId_.addAll(other.otherId_);
            }
            onChanged();
          }
        } else {
          if (!other.otherId_.isEmpty()) {
            if (otherIdBuilder_.isEmpty()) {
              otherIdBuilder_.dispose();
              otherIdBuilder_ = null;
              otherId_ = other.otherId_;
              bitField0_ = (bitField0_ & ~0x00000020);
              otherIdBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getOtherIdFieldBuilder() : null;
            } else {
              otherIdBuilder_.addAllMessages(other.otherId_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasKey()) {
          
          return false;
        }
        for (int i = 0; i < getOtherIdCount(); i++) {
          if (!getOtherId(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              key_ = input.readBytes();
              break;
            }
            case 18: {
              ensureNameIsMutable();
              name_.add(input.readBytes());
              break;
            }
            case 26: {
              ensureFirstnameIsMutable();
              firstname_.add(input.readBytes());
              break;
            }
            case 34: {
              ensureLastnameIsMutable();
              lastname_.add(input.readBytes());
              break;
            }
            case 42: {
              ensureEmailIsMutable();
              email_.add(input.readBytes());
              break;
            }
            case 50: {
              pl.edu.icm.coansys.models.DocumentProtos.KeyValue.Builder subBuilder = pl.edu.icm.coansys.models.DocumentProtos.KeyValue.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addOtherId(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string key = 1;
      private java.lang.Object key_ = "";
      public boolean hasKey() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getKey() {
        java.lang.Object ref = key_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          key_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setKey(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        key_ = value;
        onChanged();
        return this;
      }
      public Builder clearKey() {
        bitField0_ = (bitField0_ & ~0x00000001);
        key_ = getDefaultInstance().getKey();
        onChanged();
        return this;
      }
      void setKey(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        key_ = value;
        onChanged();
      }
      
      // repeated string name = 2;
      private com.google.protobuf.LazyStringList name_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureNameIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          name_ = new com.google.protobuf.LazyStringArrayList(name_);
          bitField0_ |= 0x00000002;
         }
      }
      public java.util.List<String>
          getNameList() {
        return java.util.Collections.unmodifiableList(name_);
      }
      public int getNameCount() {
        return name_.size();
      }
      public String getName(int index) {
        return name_.get(index);
      }
      public Builder setName(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureNameIsMutable();
        name_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureNameIsMutable();
        name_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllName(
          java.lang.Iterable<String> values) {
        ensureNameIsMutable();
        super.addAll(values, name_);
        onChanged();
        return this;
      }
      public Builder clearName() {
        name_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      void addName(com.google.protobuf.ByteString value) {
        ensureNameIsMutable();
        name_.add(value);
        onChanged();
      }
      
      // repeated string firstname = 3;
      private com.google.protobuf.LazyStringList firstname_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureFirstnameIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          firstname_ = new com.google.protobuf.LazyStringArrayList(firstname_);
          bitField0_ |= 0x00000004;
         }
      }
      public java.util.List<String>
          getFirstnameList() {
        return java.util.Collections.unmodifiableList(firstname_);
      }
      public int getFirstnameCount() {
        return firstname_.size();
      }
      public String getFirstname(int index) {
        return firstname_.get(index);
      }
      public Builder setFirstname(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFirstnameIsMutable();
        firstname_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addFirstname(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFirstnameIsMutable();
        firstname_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllFirstname(
          java.lang.Iterable<String> values) {
        ensureFirstnameIsMutable();
        super.addAll(values, firstname_);
        onChanged();
        return this;
      }
      public Builder clearFirstname() {
        firstname_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      void addFirstname(com.google.protobuf.ByteString value) {
        ensureFirstnameIsMutable();
        firstname_.add(value);
        onChanged();
      }
      
      // repeated string lastname = 4;
      private com.google.protobuf.LazyStringList lastname_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureLastnameIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          lastname_ = new com.google.protobuf.LazyStringArrayList(lastname_);
          bitField0_ |= 0x00000008;
         }
      }
      public java.util.List<String>
          getLastnameList() {
        return java.util.Collections.unmodifiableList(lastname_);
      }
      public int getLastnameCount() {
        return lastname_.size();
      }
      public String getLastname(int index) {
        return lastname_.get(index);
      }
      public Builder setLastname(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureLastnameIsMutable();
        lastname_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addLastname(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureLastnameIsMutable();
        lastname_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllLastname(
          java.lang.Iterable<String> values) {
        ensureLastnameIsMutable();
        super.addAll(values, lastname_);
        onChanged();
        return this;
      }
      public Builder clearLastname() {
        lastname_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      void addLastname(com.google.protobuf.ByteString value) {
        ensureLastnameIsMutable();
        lastname_.add(value);
        onChanged();
      }
      
      // repeated string email = 5;
      private com.google.protobuf.LazyStringList email_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureEmailIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          email_ = new com.google.protobuf.LazyStringArrayList(email_);
          bitField0_ |= 0x00000010;
         }
      }
      public java.util.List<String>
          getEmailList() {
        return java.util.Collections.unmodifiableList(email_);
      }
      public int getEmailCount() {
        return email_.size();
      }
      public String getEmail(int index) {
        return email_.get(index);
      }
      public Builder setEmail(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureEmailIsMutable();
        email_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addEmail(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureEmailIsMutable();
        email_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllEmail(
          java.lang.Iterable<String> values) {
        ensureEmailIsMutable();
        super.addAll(values, email_);
        onChanged();
        return this;
      }
      public Builder clearEmail() {
        email_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      void addEmail(com.google.protobuf.ByteString value) {
        ensureEmailIsMutable();
        email_.add(value);
        onChanged();
      }
      
      // repeated .KeyValue otherId = 6;
      private java.util.List<pl.edu.icm.coansys.models.DocumentProtos.KeyValue> otherId_ =
        java.util.Collections.emptyList();
      private void ensureOtherIdIsMutable() {
        if (!((bitField0_ & 0x00000020) == 0x00000020)) {
          otherId_ = new java.util.ArrayList<pl.edu.icm.coansys.models.DocumentProtos.KeyValue>(otherId_);
          bitField0_ |= 0x00000020;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          pl.edu.icm.coansys.models.DocumentProtos.KeyValue, pl.edu.icm.coansys.models.DocumentProtos.KeyValue.Builder, pl.edu.icm.coansys.models.DocumentProtos.KeyValueOrBuilder> otherIdBuilder_;
      
      public java.util.List<pl.edu.icm.coansys.models.DocumentProtos.KeyValue> getOtherIdList() {
        if (otherIdBuilder_ == null) {
          return java.util.Collections.unmodifiableList(otherId_);
        } else {
          return otherIdBuilder_.getMessageList();
        }
      }
      public int getOtherIdCount() {
        if (otherIdBuilder_ == null) {
          return otherId_.size();
        } else {
          return otherIdBuilder_.getCount();
        }
      }
      public pl.edu.icm.coansys.models.DocumentProtos.KeyValue getOtherId(int index) {
        if (otherIdBuilder_ == null) {
          return otherId_.get(index);
        } else {
          return otherIdBuilder_.getMessage(index);
        }
      }
      public Builder setOtherId(
          int index, pl.edu.icm.coansys.models.DocumentProtos.KeyValue value) {
        if (otherIdBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOtherIdIsMutable();
          otherId_.set(index, value);
          onChanged();
        } else {
          otherIdBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setOtherId(
          int index, pl.edu.icm.coansys.models.DocumentProtos.KeyValue.Builder builderForValue) {
        if (otherIdBuilder_ == null) {
          ensureOtherIdIsMutable();
          otherId_.set(index, builderForValue.build());
          onChanged();
        } else {
          otherIdBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addOtherId(pl.edu.icm.coansys.models.DocumentProtos.KeyValue value) {
        if (otherIdBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOtherIdIsMutable();
          otherId_.add(value);
          onChanged();
        } else {
          otherIdBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addOtherId(
          int index, pl.edu.icm.coansys.models.DocumentProtos.KeyValue value) {
        if (otherIdBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOtherIdIsMutable();
          otherId_.add(index, value);
          onChanged();
        } else {
          otherIdBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addOtherId(
          pl.edu.icm.coansys.models.DocumentProtos.KeyValue.Builder builderForValue) {
        if (otherIdBuilder_ == null) {
          ensureOtherIdIsMutable();
          otherId_.add(builderForValue.build());
          onChanged();
        } else {
          otherIdBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addOtherId(
          int index, pl.edu.icm.coansys.models.DocumentProtos.KeyValue.Builder builderForValue) {
        if (otherIdBuilder_ == null) {
          ensureOtherIdIsMutable();
          otherId_.add(index, builderForValue.build());
          onChanged();
        } else {
          otherIdBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllOtherId(
          java.lang.Iterable<? extends pl.edu.icm.coansys.models.DocumentProtos.KeyValue> values) {
        if (otherIdBuilder_ == null) {
          ensureOtherIdIsMutable();
          super.addAll(values, otherId_);
          onChanged();
        } else {
          otherIdBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearOtherId() {
        if (otherIdBuilder_ == null) {
          otherId_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000020);
          onChanged();
        } else {
          otherIdBuilder_.clear();
        }
        return this;
      }
      public Builder removeOtherId(int index) {
        if (otherIdBuilder_ == null) {
          ensureOtherIdIsMutable();
          otherId_.remove(index);
          onChanged();
        } else {
          otherIdBuilder_.remove(index);
        }
        return this;
      }
      public pl.edu.icm.coansys.models.DocumentProtos.KeyValue.Builder getOtherIdBuilder(
          int index) {
        return getOtherIdFieldBuilder().getBuilder(index);
      }
      public pl.edu.icm.coansys.models.DocumentProtos.KeyValueOrBuilder getOtherIdOrBuilder(
          int index) {
        if (otherIdBuilder_ == null) {
          return otherId_.get(index);  } else {
          return otherIdBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends pl.edu.icm.coansys.models.DocumentProtos.KeyValueOrBuilder> 
           getOtherIdOrBuilderList() {
        if (otherIdBuilder_ != null) {
          return otherIdBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(otherId_);
        }
      }
      public pl.edu.icm.coansys.models.DocumentProtos.KeyValue.Builder addOtherIdBuilder() {
        return getOtherIdFieldBuilder().addBuilder(
            pl.edu.icm.coansys.models.DocumentProtos.KeyValue.getDefaultInstance());
      }
      public pl.edu.icm.coansys.models.DocumentProtos.KeyValue.Builder addOtherIdBuilder(
          int index) {
        return getOtherIdFieldBuilder().addBuilder(
            index, pl.edu.icm.coansys.models.DocumentProtos.KeyValue.getDefaultInstance());
      }
      public java.util.List<pl.edu.icm.coansys.models.DocumentProtos.KeyValue.Builder> 
           getOtherIdBuilderList() {
        return getOtherIdFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          pl.edu.icm.coansys.models.DocumentProtos.KeyValue, pl.edu.icm.coansys.models.DocumentProtos.KeyValue.Builder, pl.edu.icm.coansys.models.DocumentProtos.KeyValueOrBuilder> 
          getOtherIdFieldBuilder() {
        if (otherIdBuilder_ == null) {
          otherIdBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              pl.edu.icm.coansys.models.DocumentProtos.KeyValue, pl.edu.icm.coansys.models.DocumentProtos.KeyValue.Builder, pl.edu.icm.coansys.models.DocumentProtos.KeyValueOrBuilder>(
                  otherId_,
                  ((bitField0_ & 0x00000020) == 0x00000020),
                  getParentForChildren(),
                  isClean());
          otherId_ = null;
        }
        return otherIdBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:PersonMetadata)
    }
    
    static {
      defaultInstance = new PersonMetadata(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:PersonMetadata)
  }
  
  public interface PersonWrapperOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string rowId = 1;
    boolean hasRowId();
    String getRowId();
    
    // optional .PersonMetadata personMetadata = 2;
    boolean hasPersonMetadata();
    pl.edu.icm.coansys.models.PersonProtos.PersonMetadata getPersonMetadata();
    pl.edu.icm.coansys.models.PersonProtos.PersonMetadataOrBuilder getPersonMetadataOrBuilder();
    
    // optional .MediaContainer mediaContainer = 3;
    boolean hasMediaContainer();
    pl.edu.icm.coansys.models.DocumentProtos.MediaContainer getMediaContainer();
    pl.edu.icm.coansys.models.DocumentProtos.MediaContainerOrBuilder getMediaContainerOrBuilder();
  }
  public static final class PersonWrapper extends
      com.google.protobuf.GeneratedMessage
      implements PersonWrapperOrBuilder {
    // Use PersonWrapper.newBuilder() to construct.
    private PersonWrapper(Builder builder) {
      super(builder);
    }
    private PersonWrapper(boolean noInit) {}
    
    private static final PersonWrapper defaultInstance;
    public static PersonWrapper getDefaultInstance() {
      return defaultInstance;
    }
    
    public PersonWrapper getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pl.edu.icm.coansys.models.PersonProtos.internal_static_PersonWrapper_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pl.edu.icm.coansys.models.PersonProtos.internal_static_PersonWrapper_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string rowId = 1;
    public static final int ROWID_FIELD_NUMBER = 1;
    private java.lang.Object rowId_;
    public boolean hasRowId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getRowId() {
      java.lang.Object ref = rowId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          rowId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getRowIdBytes() {
      java.lang.Object ref = rowId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        rowId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional .PersonMetadata personMetadata = 2;
    public static final int PERSONMETADATA_FIELD_NUMBER = 2;
    private pl.edu.icm.coansys.models.PersonProtos.PersonMetadata personMetadata_;
    public boolean hasPersonMetadata() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public pl.edu.icm.coansys.models.PersonProtos.PersonMetadata getPersonMetadata() {
      return personMetadata_;
    }
    public pl.edu.icm.coansys.models.PersonProtos.PersonMetadataOrBuilder getPersonMetadataOrBuilder() {
      return personMetadata_;
    }
    
    // optional .MediaContainer mediaContainer = 3;
    public static final int MEDIACONTAINER_FIELD_NUMBER = 3;
    private pl.edu.icm.coansys.models.DocumentProtos.MediaContainer mediaContainer_;
    public boolean hasMediaContainer() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public pl.edu.icm.coansys.models.DocumentProtos.MediaContainer getMediaContainer() {
      return mediaContainer_;
    }
    public pl.edu.icm.coansys.models.DocumentProtos.MediaContainerOrBuilder getMediaContainerOrBuilder() {
      return mediaContainer_;
    }
    
    private void initFields() {
      rowId_ = "";
      personMetadata_ = pl.edu.icm.coansys.models.PersonProtos.PersonMetadata.getDefaultInstance();
      mediaContainer_ = pl.edu.icm.coansys.models.DocumentProtos.MediaContainer.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasRowId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasPersonMetadata()) {
        if (!getPersonMetadata().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasMediaContainer()) {
        if (!getMediaContainer().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getRowIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, personMetadata_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, mediaContainer_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getRowIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, personMetadata_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, mediaContainer_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static pl.edu.icm.coansys.models.PersonProtos.PersonWrapper parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static pl.edu.icm.coansys.models.PersonProtos.PersonWrapper parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static pl.edu.icm.coansys.models.PersonProtos.PersonWrapper parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static pl.edu.icm.coansys.models.PersonProtos.PersonWrapper parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static pl.edu.icm.coansys.models.PersonProtos.PersonWrapper parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static pl.edu.icm.coansys.models.PersonProtos.PersonWrapper parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static pl.edu.icm.coansys.models.PersonProtos.PersonWrapper parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static pl.edu.icm.coansys.models.PersonProtos.PersonWrapper parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static pl.edu.icm.coansys.models.PersonProtos.PersonWrapper parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static pl.edu.icm.coansys.models.PersonProtos.PersonWrapper parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(pl.edu.icm.coansys.models.PersonProtos.PersonWrapper prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements pl.edu.icm.coansys.models.PersonProtos.PersonWrapperOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pl.edu.icm.coansys.models.PersonProtos.internal_static_PersonWrapper_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pl.edu.icm.coansys.models.PersonProtos.internal_static_PersonWrapper_fieldAccessorTable;
      }
      
      // Construct using pl.edu.icm.coansys.models.PersonProtos.PersonWrapper.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPersonMetadataFieldBuilder();
          getMediaContainerFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        rowId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (personMetadataBuilder_ == null) {
          personMetadata_ = pl.edu.icm.coansys.models.PersonProtos.PersonMetadata.getDefaultInstance();
        } else {
          personMetadataBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        if (mediaContainerBuilder_ == null) {
          mediaContainer_ = pl.edu.icm.coansys.models.DocumentProtos.MediaContainer.getDefaultInstance();
        } else {
          mediaContainerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pl.edu.icm.coansys.models.PersonProtos.PersonWrapper.getDescriptor();
      }
      
      public pl.edu.icm.coansys.models.PersonProtos.PersonWrapper getDefaultInstanceForType() {
        return pl.edu.icm.coansys.models.PersonProtos.PersonWrapper.getDefaultInstance();
      }
      
      public pl.edu.icm.coansys.models.PersonProtos.PersonWrapper build() {
        pl.edu.icm.coansys.models.PersonProtos.PersonWrapper result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private pl.edu.icm.coansys.models.PersonProtos.PersonWrapper buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        pl.edu.icm.coansys.models.PersonProtos.PersonWrapper result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public pl.edu.icm.coansys.models.PersonProtos.PersonWrapper buildPartial() {
        pl.edu.icm.coansys.models.PersonProtos.PersonWrapper result = new pl.edu.icm.coansys.models.PersonProtos.PersonWrapper(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.rowId_ = rowId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (personMetadataBuilder_ == null) {
          result.personMetadata_ = personMetadata_;
        } else {
          result.personMetadata_ = personMetadataBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (mediaContainerBuilder_ == null) {
          result.mediaContainer_ = mediaContainer_;
        } else {
          result.mediaContainer_ = mediaContainerBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pl.edu.icm.coansys.models.PersonProtos.PersonWrapper) {
          return mergeFrom((pl.edu.icm.coansys.models.PersonProtos.PersonWrapper)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(pl.edu.icm.coansys.models.PersonProtos.PersonWrapper other) {
        if (other == pl.edu.icm.coansys.models.PersonProtos.PersonWrapper.getDefaultInstance()) return this;
        if (other.hasRowId()) {
          setRowId(other.getRowId());
        }
        if (other.hasPersonMetadata()) {
          mergePersonMetadata(other.getPersonMetadata());
        }
        if (other.hasMediaContainer()) {
          mergeMediaContainer(other.getMediaContainer());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasRowId()) {
          
          return false;
        }
        if (hasPersonMetadata()) {
          if (!getPersonMetadata().isInitialized()) {
            
            return false;
          }
        }
        if (hasMediaContainer()) {
          if (!getMediaContainer().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              rowId_ = input.readBytes();
              break;
            }
            case 18: {
              pl.edu.icm.coansys.models.PersonProtos.PersonMetadata.Builder subBuilder = pl.edu.icm.coansys.models.PersonProtos.PersonMetadata.newBuilder();
              if (hasPersonMetadata()) {
                subBuilder.mergeFrom(getPersonMetadata());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setPersonMetadata(subBuilder.buildPartial());
              break;
            }
            case 26: {
              pl.edu.icm.coansys.models.DocumentProtos.MediaContainer.Builder subBuilder = pl.edu.icm.coansys.models.DocumentProtos.MediaContainer.newBuilder();
              if (hasMediaContainer()) {
                subBuilder.mergeFrom(getMediaContainer());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setMediaContainer(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string rowId = 1;
      private java.lang.Object rowId_ = "";
      public boolean hasRowId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getRowId() {
        java.lang.Object ref = rowId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          rowId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setRowId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        rowId_ = value;
        onChanged();
        return this;
      }
      public Builder clearRowId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        rowId_ = getDefaultInstance().getRowId();
        onChanged();
        return this;
      }
      void setRowId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        rowId_ = value;
        onChanged();
      }
      
      // optional .PersonMetadata personMetadata = 2;
      private pl.edu.icm.coansys.models.PersonProtos.PersonMetadata personMetadata_ = pl.edu.icm.coansys.models.PersonProtos.PersonMetadata.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          pl.edu.icm.coansys.models.PersonProtos.PersonMetadata, pl.edu.icm.coansys.models.PersonProtos.PersonMetadata.Builder, pl.edu.icm.coansys.models.PersonProtos.PersonMetadataOrBuilder> personMetadataBuilder_;
      public boolean hasPersonMetadata() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public pl.edu.icm.coansys.models.PersonProtos.PersonMetadata getPersonMetadata() {
        if (personMetadataBuilder_ == null) {
          return personMetadata_;
        } else {
          return personMetadataBuilder_.getMessage();
        }
      }
      public Builder setPersonMetadata(pl.edu.icm.coansys.models.PersonProtos.PersonMetadata value) {
        if (personMetadataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          personMetadata_ = value;
          onChanged();
        } else {
          personMetadataBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder setPersonMetadata(
          pl.edu.icm.coansys.models.PersonProtos.PersonMetadata.Builder builderForValue) {
        if (personMetadataBuilder_ == null) {
          personMetadata_ = builderForValue.build();
          onChanged();
        } else {
          personMetadataBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder mergePersonMetadata(pl.edu.icm.coansys.models.PersonProtos.PersonMetadata value) {
        if (personMetadataBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              personMetadata_ != pl.edu.icm.coansys.models.PersonProtos.PersonMetadata.getDefaultInstance()) {
            personMetadata_ =
              pl.edu.icm.coansys.models.PersonProtos.PersonMetadata.newBuilder(personMetadata_).mergeFrom(value).buildPartial();
          } else {
            personMetadata_ = value;
          }
          onChanged();
        } else {
          personMetadataBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder clearPersonMetadata() {
        if (personMetadataBuilder_ == null) {
          personMetadata_ = pl.edu.icm.coansys.models.PersonProtos.PersonMetadata.getDefaultInstance();
          onChanged();
        } else {
          personMetadataBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      public pl.edu.icm.coansys.models.PersonProtos.PersonMetadata.Builder getPersonMetadataBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getPersonMetadataFieldBuilder().getBuilder();
      }
      public pl.edu.icm.coansys.models.PersonProtos.PersonMetadataOrBuilder getPersonMetadataOrBuilder() {
        if (personMetadataBuilder_ != null) {
          return personMetadataBuilder_.getMessageOrBuilder();
        } else {
          return personMetadata_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          pl.edu.icm.coansys.models.PersonProtos.PersonMetadata, pl.edu.icm.coansys.models.PersonProtos.PersonMetadata.Builder, pl.edu.icm.coansys.models.PersonProtos.PersonMetadataOrBuilder> 
          getPersonMetadataFieldBuilder() {
        if (personMetadataBuilder_ == null) {
          personMetadataBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              pl.edu.icm.coansys.models.PersonProtos.PersonMetadata, pl.edu.icm.coansys.models.PersonProtos.PersonMetadata.Builder, pl.edu.icm.coansys.models.PersonProtos.PersonMetadataOrBuilder>(
                  personMetadata_,
                  getParentForChildren(),
                  isClean());
          personMetadata_ = null;
        }
        return personMetadataBuilder_;
      }
      
      // optional .MediaContainer mediaContainer = 3;
      private pl.edu.icm.coansys.models.DocumentProtos.MediaContainer mediaContainer_ = pl.edu.icm.coansys.models.DocumentProtos.MediaContainer.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          pl.edu.icm.coansys.models.DocumentProtos.MediaContainer, pl.edu.icm.coansys.models.DocumentProtos.MediaContainer.Builder, pl.edu.icm.coansys.models.DocumentProtos.MediaContainerOrBuilder> mediaContainerBuilder_;
      public boolean hasMediaContainer() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public pl.edu.icm.coansys.models.DocumentProtos.MediaContainer getMediaContainer() {
        if (mediaContainerBuilder_ == null) {
          return mediaContainer_;
        } else {
          return mediaContainerBuilder_.getMessage();
        }
      }
      public Builder setMediaContainer(pl.edu.icm.coansys.models.DocumentProtos.MediaContainer value) {
        if (mediaContainerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          mediaContainer_ = value;
          onChanged();
        } else {
          mediaContainerBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder setMediaContainer(
          pl.edu.icm.coansys.models.DocumentProtos.MediaContainer.Builder builderForValue) {
        if (mediaContainerBuilder_ == null) {
          mediaContainer_ = builderForValue.build();
          onChanged();
        } else {
          mediaContainerBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder mergeMediaContainer(pl.edu.icm.coansys.models.DocumentProtos.MediaContainer value) {
        if (mediaContainerBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              mediaContainer_ != pl.edu.icm.coansys.models.DocumentProtos.MediaContainer.getDefaultInstance()) {
            mediaContainer_ =
              pl.edu.icm.coansys.models.DocumentProtos.MediaContainer.newBuilder(mediaContainer_).mergeFrom(value).buildPartial();
          } else {
            mediaContainer_ = value;
          }
          onChanged();
        } else {
          mediaContainerBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder clearMediaContainer() {
        if (mediaContainerBuilder_ == null) {
          mediaContainer_ = pl.edu.icm.coansys.models.DocumentProtos.MediaContainer.getDefaultInstance();
          onChanged();
        } else {
          mediaContainerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      public pl.edu.icm.coansys.models.DocumentProtos.MediaContainer.Builder getMediaContainerBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getMediaContainerFieldBuilder().getBuilder();
      }
      public pl.edu.icm.coansys.models.DocumentProtos.MediaContainerOrBuilder getMediaContainerOrBuilder() {
        if (mediaContainerBuilder_ != null) {
          return mediaContainerBuilder_.getMessageOrBuilder();
        } else {
          return mediaContainer_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          pl.edu.icm.coansys.models.DocumentProtos.MediaContainer, pl.edu.icm.coansys.models.DocumentProtos.MediaContainer.Builder, pl.edu.icm.coansys.models.DocumentProtos.MediaContainerOrBuilder> 
          getMediaContainerFieldBuilder() {
        if (mediaContainerBuilder_ == null) {
          mediaContainerBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              pl.edu.icm.coansys.models.DocumentProtos.MediaContainer, pl.edu.icm.coansys.models.DocumentProtos.MediaContainer.Builder, pl.edu.icm.coansys.models.DocumentProtos.MediaContainerOrBuilder>(
                  mediaContainer_,
                  getParentForChildren(),
                  isClean());
          mediaContainer_ = null;
        }
        return mediaContainerBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:PersonWrapper)
    }
    
    static {
      defaultInstance = new PersonWrapper(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:PersonWrapper)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_PersonMetadata_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PersonMetadata_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_PersonWrapper_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PersonWrapper_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014person.proto\032\tbw2.proto\"{\n\016PersonMetad" +
      "ata\022\013\n\003key\030\001 \002(\t\022\014\n\004name\030\002 \003(\t\022\021\n\tfirstn" +
      "ame\030\003 \003(\t\022\020\n\010lastname\030\004 \003(\t\022\r\n\005email\030\005 \003" +
      "(\t\022\032\n\007otherId\030\006 \003(\0132\t.KeyValue\"p\n\rPerson" +
      "Wrapper\022\r\n\005rowId\030\001 \002(\t\022\'\n\016personMetadata" +
      "\030\002 \001(\0132\017.PersonMetadata\022\'\n\016mediaContaine" +
      "r\030\003 \001(\0132\017.MediaContainerB)\n\031pl.edu.icm.c" +
      "oansys.modelsB\014PersonProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_PersonMetadata_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_PersonMetadata_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_PersonMetadata_descriptor,
              new java.lang.String[] { "Key", "Name", "Firstname", "Lastname", "Email", "OtherId", },
              pl.edu.icm.coansys.models.PersonProtos.PersonMetadata.class,
              pl.edu.icm.coansys.models.PersonProtos.PersonMetadata.Builder.class);
          internal_static_PersonWrapper_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_PersonWrapper_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_PersonWrapper_descriptor,
              new java.lang.String[] { "RowId", "PersonMetadata", "MediaContainer", },
              pl.edu.icm.coansys.models.PersonProtos.PersonWrapper.class,
              pl.edu.icm.coansys.models.PersonProtos.PersonWrapper.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          pl.edu.icm.coansys.models.DocumentProtos.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
