// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: project.proto

package pl.edu.icm.coansys.models;

public final class ProjectProtos {
  private ProjectProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ProjectMetadataOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string key = 1;
    boolean hasKey();
    String getKey();
    
    // repeated string name = 2;
    java.util.List<String> getNameList();
    int getNameCount();
    String getName(int index);
    
    // optional string description = 3;
    boolean hasDescription();
    String getDescription();
    
    // optional string url = 4;
    boolean hasUrl();
    String getUrl();
    
    // optional string intitutionCoordinatorId = 5;
    boolean hasIntitutionCoordinatorId();
    String getIntitutionCoordinatorId();
    
    // optional string personCoordinatorId = 6;
    boolean hasPersonCoordinatorId();
    String getPersonCoordinatorId();
    
    // repeated string intitutionPartnerId = 7;
    java.util.List<String> getIntitutionPartnerIdList();
    int getIntitutionPartnerIdCount();
    String getIntitutionPartnerId(int index);
    
    // repeated string personParticipantId = 8;
    java.util.List<String> getPersonParticipantIdList();
    int getPersonParticipantIdCount();
    String getPersonParticipantId(int index);
    
    // repeated .KeyValue otherId = 9;
    java.util.List<pl.edu.icm.coansys.models.DocumentProtos.KeyValue> 
        getOtherIdList();
    pl.edu.icm.coansys.models.DocumentProtos.KeyValue getOtherId(int index);
    int getOtherIdCount();
    java.util.List<? extends pl.edu.icm.coansys.models.DocumentProtos.KeyValueOrBuilder> 
        getOtherIdOrBuilderList();
    pl.edu.icm.coansys.models.DocumentProtos.KeyValueOrBuilder getOtherIdOrBuilder(
        int index);
  }
  public static final class ProjectMetadata extends
      com.google.protobuf.GeneratedMessage
      implements ProjectMetadataOrBuilder {
    // Use ProjectMetadata.newBuilder() to construct.
    private ProjectMetadata(Builder builder) {
      super(builder);
    }
    private ProjectMetadata(boolean noInit) {}
    
    private static final ProjectMetadata defaultInstance;
    public static ProjectMetadata getDefaultInstance() {
      return defaultInstance;
    }
    
    public ProjectMetadata getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pl.edu.icm.coansys.models.ProjectProtos.internal_static_ProjectMetadata_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pl.edu.icm.coansys.models.ProjectProtos.internal_static_ProjectMetadata_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string key = 1;
    public static final int KEY_FIELD_NUMBER = 1;
    private java.lang.Object key_;
    public boolean hasKey() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getKey() {
      java.lang.Object ref = key_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          key_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated string name = 2;
    public static final int NAME_FIELD_NUMBER = 2;
    private com.google.protobuf.LazyStringList name_;
    public java.util.List<String>
        getNameList() {
      return name_;
    }
    public int getNameCount() {
      return name_.size();
    }
    public String getName(int index) {
      return name_.get(index);
    }
    
    // optional string description = 3;
    public static final int DESCRIPTION_FIELD_NUMBER = 3;
    private java.lang.Object description_;
    public boolean hasDescription() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          description_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string url = 4;
    public static final int URL_FIELD_NUMBER = 4;
    private java.lang.Object url_;
    public boolean hasUrl() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getUrl() {
      java.lang.Object ref = url_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          url_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getUrlBytes() {
      java.lang.Object ref = url_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        url_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string intitutionCoordinatorId = 5;
    public static final int INTITUTIONCOORDINATORID_FIELD_NUMBER = 5;
    private java.lang.Object intitutionCoordinatorId_;
    public boolean hasIntitutionCoordinatorId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getIntitutionCoordinatorId() {
      java.lang.Object ref = intitutionCoordinatorId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          intitutionCoordinatorId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getIntitutionCoordinatorIdBytes() {
      java.lang.Object ref = intitutionCoordinatorId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        intitutionCoordinatorId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string personCoordinatorId = 6;
    public static final int PERSONCOORDINATORID_FIELD_NUMBER = 6;
    private java.lang.Object personCoordinatorId_;
    public boolean hasPersonCoordinatorId() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public String getPersonCoordinatorId() {
      java.lang.Object ref = personCoordinatorId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          personCoordinatorId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getPersonCoordinatorIdBytes() {
      java.lang.Object ref = personCoordinatorId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        personCoordinatorId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated string intitutionPartnerId = 7;
    public static final int INTITUTIONPARTNERID_FIELD_NUMBER = 7;
    private com.google.protobuf.LazyStringList intitutionPartnerId_;
    public java.util.List<String>
        getIntitutionPartnerIdList() {
      return intitutionPartnerId_;
    }
    public int getIntitutionPartnerIdCount() {
      return intitutionPartnerId_.size();
    }
    public String getIntitutionPartnerId(int index) {
      return intitutionPartnerId_.get(index);
    }
    
    // repeated string personParticipantId = 8;
    public static final int PERSONPARTICIPANTID_FIELD_NUMBER = 8;
    private com.google.protobuf.LazyStringList personParticipantId_;
    public java.util.List<String>
        getPersonParticipantIdList() {
      return personParticipantId_;
    }
    public int getPersonParticipantIdCount() {
      return personParticipantId_.size();
    }
    public String getPersonParticipantId(int index) {
      return personParticipantId_.get(index);
    }
    
    // repeated .KeyValue otherId = 9;
    public static final int OTHERID_FIELD_NUMBER = 9;
    private java.util.List<pl.edu.icm.coansys.models.DocumentProtos.KeyValue> otherId_;
    public java.util.List<pl.edu.icm.coansys.models.DocumentProtos.KeyValue> getOtherIdList() {
      return otherId_;
    }
    public java.util.List<? extends pl.edu.icm.coansys.models.DocumentProtos.KeyValueOrBuilder> 
        getOtherIdOrBuilderList() {
      return otherId_;
    }
    public int getOtherIdCount() {
      return otherId_.size();
    }
    public pl.edu.icm.coansys.models.DocumentProtos.KeyValue getOtherId(int index) {
      return otherId_.get(index);
    }
    public pl.edu.icm.coansys.models.DocumentProtos.KeyValueOrBuilder getOtherIdOrBuilder(
        int index) {
      return otherId_.get(index);
    }
    
    private void initFields() {
      key_ = "";
      name_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      description_ = "";
      url_ = "";
      intitutionCoordinatorId_ = "";
      personCoordinatorId_ = "";
      intitutionPartnerId_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      personParticipantId_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      otherId_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasKey()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getOtherIdCount(); i++) {
        if (!getOtherId(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getKeyBytes());
      }
      for (int i = 0; i < name_.size(); i++) {
        output.writeBytes(2, name_.getByteString(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(3, getDescriptionBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(4, getUrlBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(5, getIntitutionCoordinatorIdBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(6, getPersonCoordinatorIdBytes());
      }
      for (int i = 0; i < intitutionPartnerId_.size(); i++) {
        output.writeBytes(7, intitutionPartnerId_.getByteString(i));
      }
      for (int i = 0; i < personParticipantId_.size(); i++) {
        output.writeBytes(8, personParticipantId_.getByteString(i));
      }
      for (int i = 0; i < otherId_.size(); i++) {
        output.writeMessage(9, otherId_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getKeyBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < name_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(name_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getNameList().size();
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getDescriptionBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getUrlBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getIntitutionCoordinatorIdBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getPersonCoordinatorIdBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < intitutionPartnerId_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(intitutionPartnerId_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getIntitutionPartnerIdList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < personParticipantId_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(personParticipantId_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getPersonParticipantIdList().size();
      }
      for (int i = 0; i < otherId_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(9, otherId_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static pl.edu.icm.coansys.models.ProjectProtos.ProjectMetadata parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static pl.edu.icm.coansys.models.ProjectProtos.ProjectMetadata parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static pl.edu.icm.coansys.models.ProjectProtos.ProjectMetadata parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static pl.edu.icm.coansys.models.ProjectProtos.ProjectMetadata parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static pl.edu.icm.coansys.models.ProjectProtos.ProjectMetadata parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static pl.edu.icm.coansys.models.ProjectProtos.ProjectMetadata parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static pl.edu.icm.coansys.models.ProjectProtos.ProjectMetadata parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static pl.edu.icm.coansys.models.ProjectProtos.ProjectMetadata parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static pl.edu.icm.coansys.models.ProjectProtos.ProjectMetadata parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static pl.edu.icm.coansys.models.ProjectProtos.ProjectMetadata parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(pl.edu.icm.coansys.models.ProjectProtos.ProjectMetadata prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements pl.edu.icm.coansys.models.ProjectProtos.ProjectMetadataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pl.edu.icm.coansys.models.ProjectProtos.internal_static_ProjectMetadata_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pl.edu.icm.coansys.models.ProjectProtos.internal_static_ProjectMetadata_fieldAccessorTable;
      }
      
      // Construct using pl.edu.icm.coansys.models.ProjectProtos.ProjectMetadata.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getOtherIdFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        key_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        description_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        url_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        intitutionCoordinatorId_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        personCoordinatorId_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        intitutionPartnerId_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000040);
        personParticipantId_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000080);
        if (otherIdBuilder_ == null) {
          otherId_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000100);
        } else {
          otherIdBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pl.edu.icm.coansys.models.ProjectProtos.ProjectMetadata.getDescriptor();
      }
      
      public pl.edu.icm.coansys.models.ProjectProtos.ProjectMetadata getDefaultInstanceForType() {
        return pl.edu.icm.coansys.models.ProjectProtos.ProjectMetadata.getDefaultInstance();
      }
      
      public pl.edu.icm.coansys.models.ProjectProtos.ProjectMetadata build() {
        pl.edu.icm.coansys.models.ProjectProtos.ProjectMetadata result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private pl.edu.icm.coansys.models.ProjectProtos.ProjectMetadata buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        pl.edu.icm.coansys.models.ProjectProtos.ProjectMetadata result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public pl.edu.icm.coansys.models.ProjectProtos.ProjectMetadata buildPartial() {
        pl.edu.icm.coansys.models.ProjectProtos.ProjectMetadata result = new pl.edu.icm.coansys.models.ProjectProtos.ProjectMetadata(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.key_ = key_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          name_ = new com.google.protobuf.UnmodifiableLazyStringList(
              name_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000002;
        }
        result.description_ = description_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000004;
        }
        result.url_ = url_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000008;
        }
        result.intitutionCoordinatorId_ = intitutionCoordinatorId_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000010;
        }
        result.personCoordinatorId_ = personCoordinatorId_;
        if (((bitField0_ & 0x00000040) == 0x00000040)) {
          intitutionPartnerId_ = new com.google.protobuf.UnmodifiableLazyStringList(
              intitutionPartnerId_);
          bitField0_ = (bitField0_ & ~0x00000040);
        }
        result.intitutionPartnerId_ = intitutionPartnerId_;
        if (((bitField0_ & 0x00000080) == 0x00000080)) {
          personParticipantId_ = new com.google.protobuf.UnmodifiableLazyStringList(
              personParticipantId_);
          bitField0_ = (bitField0_ & ~0x00000080);
        }
        result.personParticipantId_ = personParticipantId_;
        if (otherIdBuilder_ == null) {
          if (((bitField0_ & 0x00000100) == 0x00000100)) {
            otherId_ = java.util.Collections.unmodifiableList(otherId_);
            bitField0_ = (bitField0_ & ~0x00000100);
          }
          result.otherId_ = otherId_;
        } else {
          result.otherId_ = otherIdBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pl.edu.icm.coansys.models.ProjectProtos.ProjectMetadata) {
          return mergeFrom((pl.edu.icm.coansys.models.ProjectProtos.ProjectMetadata)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(pl.edu.icm.coansys.models.ProjectProtos.ProjectMetadata other) {
        if (other == pl.edu.icm.coansys.models.ProjectProtos.ProjectMetadata.getDefaultInstance()) return this;
        if (other.hasKey()) {
          setKey(other.getKey());
        }
        if (!other.name_.isEmpty()) {
          if (name_.isEmpty()) {
            name_ = other.name_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureNameIsMutable();
            name_.addAll(other.name_);
          }
          onChanged();
        }
        if (other.hasDescription()) {
          setDescription(other.getDescription());
        }
        if (other.hasUrl()) {
          setUrl(other.getUrl());
        }
        if (other.hasIntitutionCoordinatorId()) {
          setIntitutionCoordinatorId(other.getIntitutionCoordinatorId());
        }
        if (other.hasPersonCoordinatorId()) {
          setPersonCoordinatorId(other.getPersonCoordinatorId());
        }
        if (!other.intitutionPartnerId_.isEmpty()) {
          if (intitutionPartnerId_.isEmpty()) {
            intitutionPartnerId_ = other.intitutionPartnerId_;
            bitField0_ = (bitField0_ & ~0x00000040);
          } else {
            ensureIntitutionPartnerIdIsMutable();
            intitutionPartnerId_.addAll(other.intitutionPartnerId_);
          }
          onChanged();
        }
        if (!other.personParticipantId_.isEmpty()) {
          if (personParticipantId_.isEmpty()) {
            personParticipantId_ = other.personParticipantId_;
            bitField0_ = (bitField0_ & ~0x00000080);
          } else {
            ensurePersonParticipantIdIsMutable();
            personParticipantId_.addAll(other.personParticipantId_);
          }
          onChanged();
        }
        if (otherIdBuilder_ == null) {
          if (!other.otherId_.isEmpty()) {
            if (otherId_.isEmpty()) {
              otherId_ = other.otherId_;
              bitField0_ = (bitField0_ & ~0x00000100);
            } else {
              ensureOtherIdIsMutable();
              otherId_.addAll(other.otherId_);
            }
            onChanged();
          }
        } else {
          if (!other.otherId_.isEmpty()) {
            if (otherIdBuilder_.isEmpty()) {
              otherIdBuilder_.dispose();
              otherIdBuilder_ = null;
              otherId_ = other.otherId_;
              bitField0_ = (bitField0_ & ~0x00000100);
              otherIdBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getOtherIdFieldBuilder() : null;
            } else {
              otherIdBuilder_.addAllMessages(other.otherId_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasKey()) {
          
          return false;
        }
        for (int i = 0; i < getOtherIdCount(); i++) {
          if (!getOtherId(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              key_ = input.readBytes();
              break;
            }
            case 18: {
              ensureNameIsMutable();
              name_.add(input.readBytes());
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              description_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              url_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              intitutionCoordinatorId_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              personCoordinatorId_ = input.readBytes();
              break;
            }
            case 58: {
              ensureIntitutionPartnerIdIsMutable();
              intitutionPartnerId_.add(input.readBytes());
              break;
            }
            case 66: {
              ensurePersonParticipantIdIsMutable();
              personParticipantId_.add(input.readBytes());
              break;
            }
            case 74: {
              pl.edu.icm.coansys.models.DocumentProtos.KeyValue.Builder subBuilder = pl.edu.icm.coansys.models.DocumentProtos.KeyValue.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addOtherId(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string key = 1;
      private java.lang.Object key_ = "";
      public boolean hasKey() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getKey() {
        java.lang.Object ref = key_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          key_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setKey(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        key_ = value;
        onChanged();
        return this;
      }
      public Builder clearKey() {
        bitField0_ = (bitField0_ & ~0x00000001);
        key_ = getDefaultInstance().getKey();
        onChanged();
        return this;
      }
      void setKey(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        key_ = value;
        onChanged();
      }
      
      // repeated string name = 2;
      private com.google.protobuf.LazyStringList name_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureNameIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          name_ = new com.google.protobuf.LazyStringArrayList(name_);
          bitField0_ |= 0x00000002;
         }
      }
      public java.util.List<String>
          getNameList() {
        return java.util.Collections.unmodifiableList(name_);
      }
      public int getNameCount() {
        return name_.size();
      }
      public String getName(int index) {
        return name_.get(index);
      }
      public Builder setName(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureNameIsMutable();
        name_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureNameIsMutable();
        name_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllName(
          java.lang.Iterable<String> values) {
        ensureNameIsMutable();
        super.addAll(values, name_);
        onChanged();
        return this;
      }
      public Builder clearName() {
        name_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      void addName(com.google.protobuf.ByteString value) {
        ensureNameIsMutable();
        name_.add(value);
        onChanged();
      }
      
      // optional string description = 3;
      private java.lang.Object description_ = "";
      public boolean hasDescription() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setDescription(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        description_ = value;
        onChanged();
        return this;
      }
      public Builder clearDescription() {
        bitField0_ = (bitField0_ & ~0x00000004);
        description_ = getDefaultInstance().getDescription();
        onChanged();
        return this;
      }
      void setDescription(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        description_ = value;
        onChanged();
      }
      
      // optional string url = 4;
      private java.lang.Object url_ = "";
      public boolean hasUrl() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getUrl() {
        java.lang.Object ref = url_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          url_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setUrl(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        url_ = value;
        onChanged();
        return this;
      }
      public Builder clearUrl() {
        bitField0_ = (bitField0_ & ~0x00000008);
        url_ = getDefaultInstance().getUrl();
        onChanged();
        return this;
      }
      void setUrl(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        url_ = value;
        onChanged();
      }
      
      // optional string intitutionCoordinatorId = 5;
      private java.lang.Object intitutionCoordinatorId_ = "";
      public boolean hasIntitutionCoordinatorId() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public String getIntitutionCoordinatorId() {
        java.lang.Object ref = intitutionCoordinatorId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          intitutionCoordinatorId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setIntitutionCoordinatorId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        intitutionCoordinatorId_ = value;
        onChanged();
        return this;
      }
      public Builder clearIntitutionCoordinatorId() {
        bitField0_ = (bitField0_ & ~0x00000010);
        intitutionCoordinatorId_ = getDefaultInstance().getIntitutionCoordinatorId();
        onChanged();
        return this;
      }
      void setIntitutionCoordinatorId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000010;
        intitutionCoordinatorId_ = value;
        onChanged();
      }
      
      // optional string personCoordinatorId = 6;
      private java.lang.Object personCoordinatorId_ = "";
      public boolean hasPersonCoordinatorId() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public String getPersonCoordinatorId() {
        java.lang.Object ref = personCoordinatorId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          personCoordinatorId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setPersonCoordinatorId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        personCoordinatorId_ = value;
        onChanged();
        return this;
      }
      public Builder clearPersonCoordinatorId() {
        bitField0_ = (bitField0_ & ~0x00000020);
        personCoordinatorId_ = getDefaultInstance().getPersonCoordinatorId();
        onChanged();
        return this;
      }
      void setPersonCoordinatorId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000020;
        personCoordinatorId_ = value;
        onChanged();
      }
      
      // repeated string intitutionPartnerId = 7;
      private com.google.protobuf.LazyStringList intitutionPartnerId_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureIntitutionPartnerIdIsMutable() {
        if (!((bitField0_ & 0x00000040) == 0x00000040)) {
          intitutionPartnerId_ = new com.google.protobuf.LazyStringArrayList(intitutionPartnerId_);
          bitField0_ |= 0x00000040;
         }
      }
      public java.util.List<String>
          getIntitutionPartnerIdList() {
        return java.util.Collections.unmodifiableList(intitutionPartnerId_);
      }
      public int getIntitutionPartnerIdCount() {
        return intitutionPartnerId_.size();
      }
      public String getIntitutionPartnerId(int index) {
        return intitutionPartnerId_.get(index);
      }
      public Builder setIntitutionPartnerId(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureIntitutionPartnerIdIsMutable();
        intitutionPartnerId_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addIntitutionPartnerId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureIntitutionPartnerIdIsMutable();
        intitutionPartnerId_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllIntitutionPartnerId(
          java.lang.Iterable<String> values) {
        ensureIntitutionPartnerIdIsMutable();
        super.addAll(values, intitutionPartnerId_);
        onChanged();
        return this;
      }
      public Builder clearIntitutionPartnerId() {
        intitutionPartnerId_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
        return this;
      }
      void addIntitutionPartnerId(com.google.protobuf.ByteString value) {
        ensureIntitutionPartnerIdIsMutable();
        intitutionPartnerId_.add(value);
        onChanged();
      }
      
      // repeated string personParticipantId = 8;
      private com.google.protobuf.LazyStringList personParticipantId_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensurePersonParticipantIdIsMutable() {
        if (!((bitField0_ & 0x00000080) == 0x00000080)) {
          personParticipantId_ = new com.google.protobuf.LazyStringArrayList(personParticipantId_);
          bitField0_ |= 0x00000080;
         }
      }
      public java.util.List<String>
          getPersonParticipantIdList() {
        return java.util.Collections.unmodifiableList(personParticipantId_);
      }
      public int getPersonParticipantIdCount() {
        return personParticipantId_.size();
      }
      public String getPersonParticipantId(int index) {
        return personParticipantId_.get(index);
      }
      public Builder setPersonParticipantId(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePersonParticipantIdIsMutable();
        personParticipantId_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addPersonParticipantId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePersonParticipantIdIsMutable();
        personParticipantId_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllPersonParticipantId(
          java.lang.Iterable<String> values) {
        ensurePersonParticipantIdIsMutable();
        super.addAll(values, personParticipantId_);
        onChanged();
        return this;
      }
      public Builder clearPersonParticipantId() {
        personParticipantId_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000080);
        onChanged();
        return this;
      }
      void addPersonParticipantId(com.google.protobuf.ByteString value) {
        ensurePersonParticipantIdIsMutable();
        personParticipantId_.add(value);
        onChanged();
      }
      
      // repeated .KeyValue otherId = 9;
      private java.util.List<pl.edu.icm.coansys.models.DocumentProtos.KeyValue> otherId_ =
        java.util.Collections.emptyList();
      private void ensureOtherIdIsMutable() {
        if (!((bitField0_ & 0x00000100) == 0x00000100)) {
          otherId_ = new java.util.ArrayList<pl.edu.icm.coansys.models.DocumentProtos.KeyValue>(otherId_);
          bitField0_ |= 0x00000100;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          pl.edu.icm.coansys.models.DocumentProtos.KeyValue, pl.edu.icm.coansys.models.DocumentProtos.KeyValue.Builder, pl.edu.icm.coansys.models.DocumentProtos.KeyValueOrBuilder> otherIdBuilder_;
      
      public java.util.List<pl.edu.icm.coansys.models.DocumentProtos.KeyValue> getOtherIdList() {
        if (otherIdBuilder_ == null) {
          return java.util.Collections.unmodifiableList(otherId_);
        } else {
          return otherIdBuilder_.getMessageList();
        }
      }
      public int getOtherIdCount() {
        if (otherIdBuilder_ == null) {
          return otherId_.size();
        } else {
          return otherIdBuilder_.getCount();
        }
      }
      public pl.edu.icm.coansys.models.DocumentProtos.KeyValue getOtherId(int index) {
        if (otherIdBuilder_ == null) {
          return otherId_.get(index);
        } else {
          return otherIdBuilder_.getMessage(index);
        }
      }
      public Builder setOtherId(
          int index, pl.edu.icm.coansys.models.DocumentProtos.KeyValue value) {
        if (otherIdBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOtherIdIsMutable();
          otherId_.set(index, value);
          onChanged();
        } else {
          otherIdBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setOtherId(
          int index, pl.edu.icm.coansys.models.DocumentProtos.KeyValue.Builder builderForValue) {
        if (otherIdBuilder_ == null) {
          ensureOtherIdIsMutable();
          otherId_.set(index, builderForValue.build());
          onChanged();
        } else {
          otherIdBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addOtherId(pl.edu.icm.coansys.models.DocumentProtos.KeyValue value) {
        if (otherIdBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOtherIdIsMutable();
          otherId_.add(value);
          onChanged();
        } else {
          otherIdBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addOtherId(
          int index, pl.edu.icm.coansys.models.DocumentProtos.KeyValue value) {
        if (otherIdBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOtherIdIsMutable();
          otherId_.add(index, value);
          onChanged();
        } else {
          otherIdBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addOtherId(
          pl.edu.icm.coansys.models.DocumentProtos.KeyValue.Builder builderForValue) {
        if (otherIdBuilder_ == null) {
          ensureOtherIdIsMutable();
          otherId_.add(builderForValue.build());
          onChanged();
        } else {
          otherIdBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addOtherId(
          int index, pl.edu.icm.coansys.models.DocumentProtos.KeyValue.Builder builderForValue) {
        if (otherIdBuilder_ == null) {
          ensureOtherIdIsMutable();
          otherId_.add(index, builderForValue.build());
          onChanged();
        } else {
          otherIdBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllOtherId(
          java.lang.Iterable<? extends pl.edu.icm.coansys.models.DocumentProtos.KeyValue> values) {
        if (otherIdBuilder_ == null) {
          ensureOtherIdIsMutable();
          super.addAll(values, otherId_);
          onChanged();
        } else {
          otherIdBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearOtherId() {
        if (otherIdBuilder_ == null) {
          otherId_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000100);
          onChanged();
        } else {
          otherIdBuilder_.clear();
        }
        return this;
      }
      public Builder removeOtherId(int index) {
        if (otherIdBuilder_ == null) {
          ensureOtherIdIsMutable();
          otherId_.remove(index);
          onChanged();
        } else {
          otherIdBuilder_.remove(index);
        }
        return this;
      }
      public pl.edu.icm.coansys.models.DocumentProtos.KeyValue.Builder getOtherIdBuilder(
          int index) {
        return getOtherIdFieldBuilder().getBuilder(index);
      }
      public pl.edu.icm.coansys.models.DocumentProtos.KeyValueOrBuilder getOtherIdOrBuilder(
          int index) {
        if (otherIdBuilder_ == null) {
          return otherId_.get(index);  } else {
          return otherIdBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends pl.edu.icm.coansys.models.DocumentProtos.KeyValueOrBuilder> 
           getOtherIdOrBuilderList() {
        if (otherIdBuilder_ != null) {
          return otherIdBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(otherId_);
        }
      }
      public pl.edu.icm.coansys.models.DocumentProtos.KeyValue.Builder addOtherIdBuilder() {
        return getOtherIdFieldBuilder().addBuilder(
            pl.edu.icm.coansys.models.DocumentProtos.KeyValue.getDefaultInstance());
      }
      public pl.edu.icm.coansys.models.DocumentProtos.KeyValue.Builder addOtherIdBuilder(
          int index) {
        return getOtherIdFieldBuilder().addBuilder(
            index, pl.edu.icm.coansys.models.DocumentProtos.KeyValue.getDefaultInstance());
      }
      public java.util.List<pl.edu.icm.coansys.models.DocumentProtos.KeyValue.Builder> 
           getOtherIdBuilderList() {
        return getOtherIdFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          pl.edu.icm.coansys.models.DocumentProtos.KeyValue, pl.edu.icm.coansys.models.DocumentProtos.KeyValue.Builder, pl.edu.icm.coansys.models.DocumentProtos.KeyValueOrBuilder> 
          getOtherIdFieldBuilder() {
        if (otherIdBuilder_ == null) {
          otherIdBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              pl.edu.icm.coansys.models.DocumentProtos.KeyValue, pl.edu.icm.coansys.models.DocumentProtos.KeyValue.Builder, pl.edu.icm.coansys.models.DocumentProtos.KeyValueOrBuilder>(
                  otherId_,
                  ((bitField0_ & 0x00000100) == 0x00000100),
                  getParentForChildren(),
                  isClean());
          otherId_ = null;
        }
        return otherIdBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:ProjectMetadata)
    }
    
    static {
      defaultInstance = new ProjectMetadata(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:ProjectMetadata)
  }
  
  public interface ProjectWrapperOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string rowId = 1;
    boolean hasRowId();
    String getRowId();
    
    // optional .ProjectMetadata projectMetadata = 2;
    boolean hasProjectMetadata();
    pl.edu.icm.coansys.models.ProjectProtos.ProjectMetadata getProjectMetadata();
    pl.edu.icm.coansys.models.ProjectProtos.ProjectMetadataOrBuilder getProjectMetadataOrBuilder();
    
    // optional .MediaContainer mediaContainer = 3;
    boolean hasMediaContainer();
    pl.edu.icm.coansys.models.DocumentProtos.MediaContainer getMediaContainer();
    pl.edu.icm.coansys.models.DocumentProtos.MediaContainerOrBuilder getMediaContainerOrBuilder();
  }
  public static final class ProjectWrapper extends
      com.google.protobuf.GeneratedMessage
      implements ProjectWrapperOrBuilder {
    // Use ProjectWrapper.newBuilder() to construct.
    private ProjectWrapper(Builder builder) {
      super(builder);
    }
    private ProjectWrapper(boolean noInit) {}
    
    private static final ProjectWrapper defaultInstance;
    public static ProjectWrapper getDefaultInstance() {
      return defaultInstance;
    }
    
    public ProjectWrapper getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pl.edu.icm.coansys.models.ProjectProtos.internal_static_ProjectWrapper_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pl.edu.icm.coansys.models.ProjectProtos.internal_static_ProjectWrapper_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string rowId = 1;
    public static final int ROWID_FIELD_NUMBER = 1;
    private java.lang.Object rowId_;
    public boolean hasRowId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getRowId() {
      java.lang.Object ref = rowId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          rowId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getRowIdBytes() {
      java.lang.Object ref = rowId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        rowId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional .ProjectMetadata projectMetadata = 2;
    public static final int PROJECTMETADATA_FIELD_NUMBER = 2;
    private pl.edu.icm.coansys.models.ProjectProtos.ProjectMetadata projectMetadata_;
    public boolean hasProjectMetadata() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public pl.edu.icm.coansys.models.ProjectProtos.ProjectMetadata getProjectMetadata() {
      return projectMetadata_;
    }
    public pl.edu.icm.coansys.models.ProjectProtos.ProjectMetadataOrBuilder getProjectMetadataOrBuilder() {
      return projectMetadata_;
    }
    
    // optional .MediaContainer mediaContainer = 3;
    public static final int MEDIACONTAINER_FIELD_NUMBER = 3;
    private pl.edu.icm.coansys.models.DocumentProtos.MediaContainer mediaContainer_;
    public boolean hasMediaContainer() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public pl.edu.icm.coansys.models.DocumentProtos.MediaContainer getMediaContainer() {
      return mediaContainer_;
    }
    public pl.edu.icm.coansys.models.DocumentProtos.MediaContainerOrBuilder getMediaContainerOrBuilder() {
      return mediaContainer_;
    }
    
    private void initFields() {
      rowId_ = "";
      projectMetadata_ = pl.edu.icm.coansys.models.ProjectProtos.ProjectMetadata.getDefaultInstance();
      mediaContainer_ = pl.edu.icm.coansys.models.DocumentProtos.MediaContainer.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasRowId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasProjectMetadata()) {
        if (!getProjectMetadata().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasMediaContainer()) {
        if (!getMediaContainer().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getRowIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, projectMetadata_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, mediaContainer_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getRowIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, projectMetadata_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, mediaContainer_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static pl.edu.icm.coansys.models.ProjectProtos.ProjectWrapper parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static pl.edu.icm.coansys.models.ProjectProtos.ProjectWrapper parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static pl.edu.icm.coansys.models.ProjectProtos.ProjectWrapper parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static pl.edu.icm.coansys.models.ProjectProtos.ProjectWrapper parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static pl.edu.icm.coansys.models.ProjectProtos.ProjectWrapper parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static pl.edu.icm.coansys.models.ProjectProtos.ProjectWrapper parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static pl.edu.icm.coansys.models.ProjectProtos.ProjectWrapper parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static pl.edu.icm.coansys.models.ProjectProtos.ProjectWrapper parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static pl.edu.icm.coansys.models.ProjectProtos.ProjectWrapper parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static pl.edu.icm.coansys.models.ProjectProtos.ProjectWrapper parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(pl.edu.icm.coansys.models.ProjectProtos.ProjectWrapper prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements pl.edu.icm.coansys.models.ProjectProtos.ProjectWrapperOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pl.edu.icm.coansys.models.ProjectProtos.internal_static_ProjectWrapper_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pl.edu.icm.coansys.models.ProjectProtos.internal_static_ProjectWrapper_fieldAccessorTable;
      }
      
      // Construct using pl.edu.icm.coansys.models.ProjectProtos.ProjectWrapper.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getProjectMetadataFieldBuilder();
          getMediaContainerFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        rowId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (projectMetadataBuilder_ == null) {
          projectMetadata_ = pl.edu.icm.coansys.models.ProjectProtos.ProjectMetadata.getDefaultInstance();
        } else {
          projectMetadataBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        if (mediaContainerBuilder_ == null) {
          mediaContainer_ = pl.edu.icm.coansys.models.DocumentProtos.MediaContainer.getDefaultInstance();
        } else {
          mediaContainerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pl.edu.icm.coansys.models.ProjectProtos.ProjectWrapper.getDescriptor();
      }
      
      public pl.edu.icm.coansys.models.ProjectProtos.ProjectWrapper getDefaultInstanceForType() {
        return pl.edu.icm.coansys.models.ProjectProtos.ProjectWrapper.getDefaultInstance();
      }
      
      public pl.edu.icm.coansys.models.ProjectProtos.ProjectWrapper build() {
        pl.edu.icm.coansys.models.ProjectProtos.ProjectWrapper result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private pl.edu.icm.coansys.models.ProjectProtos.ProjectWrapper buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        pl.edu.icm.coansys.models.ProjectProtos.ProjectWrapper result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public pl.edu.icm.coansys.models.ProjectProtos.ProjectWrapper buildPartial() {
        pl.edu.icm.coansys.models.ProjectProtos.ProjectWrapper result = new pl.edu.icm.coansys.models.ProjectProtos.ProjectWrapper(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.rowId_ = rowId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (projectMetadataBuilder_ == null) {
          result.projectMetadata_ = projectMetadata_;
        } else {
          result.projectMetadata_ = projectMetadataBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (mediaContainerBuilder_ == null) {
          result.mediaContainer_ = mediaContainer_;
        } else {
          result.mediaContainer_ = mediaContainerBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pl.edu.icm.coansys.models.ProjectProtos.ProjectWrapper) {
          return mergeFrom((pl.edu.icm.coansys.models.ProjectProtos.ProjectWrapper)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(pl.edu.icm.coansys.models.ProjectProtos.ProjectWrapper other) {
        if (other == pl.edu.icm.coansys.models.ProjectProtos.ProjectWrapper.getDefaultInstance()) return this;
        if (other.hasRowId()) {
          setRowId(other.getRowId());
        }
        if (other.hasProjectMetadata()) {
          mergeProjectMetadata(other.getProjectMetadata());
        }
        if (other.hasMediaContainer()) {
          mergeMediaContainer(other.getMediaContainer());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasRowId()) {
          
          return false;
        }
        if (hasProjectMetadata()) {
          if (!getProjectMetadata().isInitialized()) {
            
            return false;
          }
        }
        if (hasMediaContainer()) {
          if (!getMediaContainer().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              rowId_ = input.readBytes();
              break;
            }
            case 18: {
              pl.edu.icm.coansys.models.ProjectProtos.ProjectMetadata.Builder subBuilder = pl.edu.icm.coansys.models.ProjectProtos.ProjectMetadata.newBuilder();
              if (hasProjectMetadata()) {
                subBuilder.mergeFrom(getProjectMetadata());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setProjectMetadata(subBuilder.buildPartial());
              break;
            }
            case 26: {
              pl.edu.icm.coansys.models.DocumentProtos.MediaContainer.Builder subBuilder = pl.edu.icm.coansys.models.DocumentProtos.MediaContainer.newBuilder();
              if (hasMediaContainer()) {
                subBuilder.mergeFrom(getMediaContainer());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setMediaContainer(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string rowId = 1;
      private java.lang.Object rowId_ = "";
      public boolean hasRowId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getRowId() {
        java.lang.Object ref = rowId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          rowId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setRowId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        rowId_ = value;
        onChanged();
        return this;
      }
      public Builder clearRowId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        rowId_ = getDefaultInstance().getRowId();
        onChanged();
        return this;
      }
      void setRowId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        rowId_ = value;
        onChanged();
      }
      
      // optional .ProjectMetadata projectMetadata = 2;
      private pl.edu.icm.coansys.models.ProjectProtos.ProjectMetadata projectMetadata_ = pl.edu.icm.coansys.models.ProjectProtos.ProjectMetadata.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          pl.edu.icm.coansys.models.ProjectProtos.ProjectMetadata, pl.edu.icm.coansys.models.ProjectProtos.ProjectMetadata.Builder, pl.edu.icm.coansys.models.ProjectProtos.ProjectMetadataOrBuilder> projectMetadataBuilder_;
      public boolean hasProjectMetadata() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public pl.edu.icm.coansys.models.ProjectProtos.ProjectMetadata getProjectMetadata() {
        if (projectMetadataBuilder_ == null) {
          return projectMetadata_;
        } else {
          return projectMetadataBuilder_.getMessage();
        }
      }
      public Builder setProjectMetadata(pl.edu.icm.coansys.models.ProjectProtos.ProjectMetadata value) {
        if (projectMetadataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          projectMetadata_ = value;
          onChanged();
        } else {
          projectMetadataBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder setProjectMetadata(
          pl.edu.icm.coansys.models.ProjectProtos.ProjectMetadata.Builder builderForValue) {
        if (projectMetadataBuilder_ == null) {
          projectMetadata_ = builderForValue.build();
          onChanged();
        } else {
          projectMetadataBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder mergeProjectMetadata(pl.edu.icm.coansys.models.ProjectProtos.ProjectMetadata value) {
        if (projectMetadataBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              projectMetadata_ != pl.edu.icm.coansys.models.ProjectProtos.ProjectMetadata.getDefaultInstance()) {
            projectMetadata_ =
              pl.edu.icm.coansys.models.ProjectProtos.ProjectMetadata.newBuilder(projectMetadata_).mergeFrom(value).buildPartial();
          } else {
            projectMetadata_ = value;
          }
          onChanged();
        } else {
          projectMetadataBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder clearProjectMetadata() {
        if (projectMetadataBuilder_ == null) {
          projectMetadata_ = pl.edu.icm.coansys.models.ProjectProtos.ProjectMetadata.getDefaultInstance();
          onChanged();
        } else {
          projectMetadataBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      public pl.edu.icm.coansys.models.ProjectProtos.ProjectMetadata.Builder getProjectMetadataBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getProjectMetadataFieldBuilder().getBuilder();
      }
      public pl.edu.icm.coansys.models.ProjectProtos.ProjectMetadataOrBuilder getProjectMetadataOrBuilder() {
        if (projectMetadataBuilder_ != null) {
          return projectMetadataBuilder_.getMessageOrBuilder();
        } else {
          return projectMetadata_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          pl.edu.icm.coansys.models.ProjectProtos.ProjectMetadata, pl.edu.icm.coansys.models.ProjectProtos.ProjectMetadata.Builder, pl.edu.icm.coansys.models.ProjectProtos.ProjectMetadataOrBuilder> 
          getProjectMetadataFieldBuilder() {
        if (projectMetadataBuilder_ == null) {
          projectMetadataBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              pl.edu.icm.coansys.models.ProjectProtos.ProjectMetadata, pl.edu.icm.coansys.models.ProjectProtos.ProjectMetadata.Builder, pl.edu.icm.coansys.models.ProjectProtos.ProjectMetadataOrBuilder>(
                  projectMetadata_,
                  getParentForChildren(),
                  isClean());
          projectMetadata_ = null;
        }
        return projectMetadataBuilder_;
      }
      
      // optional .MediaContainer mediaContainer = 3;
      private pl.edu.icm.coansys.models.DocumentProtos.MediaContainer mediaContainer_ = pl.edu.icm.coansys.models.DocumentProtos.MediaContainer.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          pl.edu.icm.coansys.models.DocumentProtos.MediaContainer, pl.edu.icm.coansys.models.DocumentProtos.MediaContainer.Builder, pl.edu.icm.coansys.models.DocumentProtos.MediaContainerOrBuilder> mediaContainerBuilder_;
      public boolean hasMediaContainer() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public pl.edu.icm.coansys.models.DocumentProtos.MediaContainer getMediaContainer() {
        if (mediaContainerBuilder_ == null) {
          return mediaContainer_;
        } else {
          return mediaContainerBuilder_.getMessage();
        }
      }
      public Builder setMediaContainer(pl.edu.icm.coansys.models.DocumentProtos.MediaContainer value) {
        if (mediaContainerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          mediaContainer_ = value;
          onChanged();
        } else {
          mediaContainerBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder setMediaContainer(
          pl.edu.icm.coansys.models.DocumentProtos.MediaContainer.Builder builderForValue) {
        if (mediaContainerBuilder_ == null) {
          mediaContainer_ = builderForValue.build();
          onChanged();
        } else {
          mediaContainerBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder mergeMediaContainer(pl.edu.icm.coansys.models.DocumentProtos.MediaContainer value) {
        if (mediaContainerBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              mediaContainer_ != pl.edu.icm.coansys.models.DocumentProtos.MediaContainer.getDefaultInstance()) {
            mediaContainer_ =
              pl.edu.icm.coansys.models.DocumentProtos.MediaContainer.newBuilder(mediaContainer_).mergeFrom(value).buildPartial();
          } else {
            mediaContainer_ = value;
          }
          onChanged();
        } else {
          mediaContainerBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder clearMediaContainer() {
        if (mediaContainerBuilder_ == null) {
          mediaContainer_ = pl.edu.icm.coansys.models.DocumentProtos.MediaContainer.getDefaultInstance();
          onChanged();
        } else {
          mediaContainerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      public pl.edu.icm.coansys.models.DocumentProtos.MediaContainer.Builder getMediaContainerBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getMediaContainerFieldBuilder().getBuilder();
      }
      public pl.edu.icm.coansys.models.DocumentProtos.MediaContainerOrBuilder getMediaContainerOrBuilder() {
        if (mediaContainerBuilder_ != null) {
          return mediaContainerBuilder_.getMessageOrBuilder();
        } else {
          return mediaContainer_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          pl.edu.icm.coansys.models.DocumentProtos.MediaContainer, pl.edu.icm.coansys.models.DocumentProtos.MediaContainer.Builder, pl.edu.icm.coansys.models.DocumentProtos.MediaContainerOrBuilder> 
          getMediaContainerFieldBuilder() {
        if (mediaContainerBuilder_ == null) {
          mediaContainerBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              pl.edu.icm.coansys.models.DocumentProtos.MediaContainer, pl.edu.icm.coansys.models.DocumentProtos.MediaContainer.Builder, pl.edu.icm.coansys.models.DocumentProtos.MediaContainerOrBuilder>(
                  mediaContainer_,
                  getParentForChildren(),
                  isClean());
          mediaContainer_ = null;
        }
        return mediaContainerBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:ProjectWrapper)
    }
    
    static {
      defaultInstance = new ProjectWrapper(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:ProjectWrapper)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ProjectMetadata_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ProjectMetadata_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ProjectWrapper_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ProjectWrapper_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rproject.proto\032\tbw2.proto\"\342\001\n\017ProjectMe" +
      "tadata\022\013\n\003key\030\001 \002(\t\022\014\n\004name\030\002 \003(\t\022\023\n\013des" +
      "cription\030\003 \001(\t\022\013\n\003url\030\004 \001(\t\022\037\n\027intitutio" +
      "nCoordinatorId\030\005 \001(\t\022\033\n\023personCoordinato" +
      "rId\030\006 \001(\t\022\033\n\023intitutionPartnerId\030\007 \003(\t\022\033" +
      "\n\023personParticipantId\030\010 \003(\t\022\032\n\007otherId\030\t" +
      " \003(\0132\t.KeyValue\"s\n\016ProjectWrapper\022\r\n\005row" +
      "Id\030\001 \002(\t\022)\n\017projectMetadata\030\002 \001(\0132\020.Proj" +
      "ectMetadata\022\'\n\016mediaContainer\030\003 \001(\0132\017.Me" +
      "diaContainerB*\n\031pl.edu.icm.coansys.model",
      "sB\rProjectProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_ProjectMetadata_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_ProjectMetadata_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ProjectMetadata_descriptor,
              new java.lang.String[] { "Key", "Name", "Description", "Url", "IntitutionCoordinatorId", "PersonCoordinatorId", "IntitutionPartnerId", "PersonParticipantId", "OtherId", },
              pl.edu.icm.coansys.models.ProjectProtos.ProjectMetadata.class,
              pl.edu.icm.coansys.models.ProjectProtos.ProjectMetadata.Builder.class);
          internal_static_ProjectWrapper_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_ProjectWrapper_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ProjectWrapper_descriptor,
              new java.lang.String[] { "RowId", "ProjectMetadata", "MediaContainer", },
              pl.edu.icm.coansys.models.ProjectProtos.ProjectWrapper.class,
              pl.edu.icm.coansys.models.ProjectProtos.ProjectWrapper.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          pl.edu.icm.coansys.models.DocumentProtos.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
